-- Admin Dashboard operations hardening.
-- Adds audit logging and a compact health snapshot RPC for Bot/Dashboard ops.

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid,
  admin_email text,
  action text not null,
  entity_type text,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_idx
  on public.admin_audit_logs (created_at desc, id desc);

create index if not exists admin_audit_logs_action_idx
  on public.admin_audit_logs (action, created_at desc);

alter table public.admin_audit_logs enable row level security;

drop policy if exists "Admins can read admin audit logs" on public.admin_audit_logs;
create policy "Admins can read admin audit logs" on public.admin_audit_logs
  for select using (public.is_admin());

drop policy if exists "Admins can insert admin audit logs" on public.admin_audit_logs;
create policy "Admins can insert admin audit logs" on public.admin_audit_logs
  for insert with check (public.is_admin());

create or replace function public.admin_record_audit_log(
  p_action text,
  p_entity_type text default null,
  p_entity_id text default null,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_id bigint;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  insert into public.admin_audit_logs (
    admin_user_id,
    admin_email,
    action,
    entity_type,
    entity_id,
    metadata
  )
  values (
    auth.uid(),
    nullif(auth.jwt() ->> 'email', ''),
    nullif(btrim(coalesce(p_action, '')), ''),
    nullif(btrim(coalesce(p_entity_type, '')), ''),
    nullif(btrim(coalesce(p_entity_id, '')), ''),
    coalesce(p_metadata, '{}'::jsonb)
  )
  returning id into v_id;

  return v_id;
end;
$$;

create or replace function public.admin_ops_health_snapshot(
  p_low_stock_threshold integer default 5
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_threshold integer := greatest(0, coalesce(p_low_stock_threshold, 5));
  v_schema jsonb;
  v_settings jsonb;
  v_outbox jsonb;
  v_low_stock jsonb;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  select jsonb_build_object(
    'tables',
    jsonb_build_object(
      'products', to_regclass('public.products') is not null,
      'stock', to_regclass('public.stock') is not null,
      'orders', to_regclass('public.orders') is not null,
      'direct_orders', to_regclass('public.direct_orders') is not null,
      'settings', to_regclass('public.settings') is not null,
      'bot_product_folders', to_regclass('public.bot_product_folders') is not null,
      'bot_delivery_outbox', to_regclass('public.bot_delivery_outbox') is not null,
      'telegram_broadcast_jobs', to_regclass('public.telegram_broadcast_jobs') is not null,
      'admin_audit_logs', to_regclass('public.admin_audit_logs') is not null
    ),
    'productColumns',
    jsonb_build_object(
      'sort_position', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'products' and column_name = 'sort_position'
      ),
      'bot_folder_id', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'products' and column_name = 'bot_folder_id'
      ),
      'telegram_icon', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'products' and column_name = 'telegram_icon'
      ),
      'telegram_icon_custom_emoji_id', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'products' and column_name = 'telegram_icon_custom_emoji_id'
      ),
      'is_hidden', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'products' and column_name = 'is_hidden'
      ),
      'is_deleted', exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'products' and column_name = 'is_deleted'
      )
    ),
    'rpcs',
    jsonb_build_object(
      'get_products_with_stock', exists (
        select 1 from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'get_products_with_stock'
      ),
      'get_product_with_stock', exists (
        select 1 from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'get_product_with_stock'
      ),
      'fulfill_bot_direct_order', exists (
        select 1 from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'fulfill_bot_direct_order'
      ),
      'fulfill_bot_balance_purchase', exists (
        select 1 from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'fulfill_bot_balance_purchase'
      ),
      'admin_ops_health_snapshot', true
    )
  )
  into v_schema;

  select jsonb_object_agg(key, present)
  into v_settings
  from (
    select wanted.key, (nullif(btrim(coalesce(s.value, '')), '') is not null) as present
    from (
      values
        ('bank_name'),
        ('account_number'),
        ('account_name'),
        ('sepay_token'),
        ('binance_api_key'),
        ('binance_api_secret'),
        ('payment_notify_bot_token'),
        ('payment_notify_user_id')
    ) as wanted(key)
    left join public.settings s on s.key = wanted.key
  ) rows;

  if to_regclass('public.bot_delivery_outbox') is not null then
    execute $q$
      select jsonb_build_object(
        'available', true,
        'pending', count(*) filter (where status = 'pending'),
        'sending', count(*) filter (where status = 'sending'),
        'sent', count(*) filter (where status = 'sent'),
        'failed', count(*) filter (where status = 'failed'),
        'retryDue', count(*) filter (where status = 'pending' and next_retry_at <= now())
      )
      from public.bot_delivery_outbox
    $q$ into v_outbox;
  else
    v_outbox := jsonb_build_object('available', false, 'pending', 0, 'sending', 0, 'sent', 0, 'failed', 0, 'retryDue', 0);
  end if;

  with product_stock as (
    select
      p.id,
      p.name,
      coalesce(count(s.id) filter (where coalesce(s.sold, false) = false), 0) as available_stock
    from public.products p
    left join public.stock s on s.product_id = p.id
    where coalesce(p.is_deleted, false) = false
      and coalesce(p.is_hidden, false) = false
    group by p.id, p.name
  ),
  low_rows as (
    select *
    from product_stock
    where available_stock <= v_threshold
    order by available_stock asc, id asc
    limit 12
  )
  select jsonb_build_object(
    'threshold', v_threshold,
    'count', (select count(*) from product_stock where available_stock <= v_threshold),
    'items', coalesce(
      (
        select jsonb_agg(
          jsonb_build_object('id', id, 'name', name, 'availableStock', available_stock)
          order by available_stock asc, id asc
        )
        from low_rows
      ),
      '[]'::jsonb
    )
  )
  into v_low_stock;

  return jsonb_build_object(
    'checkedAt', now(),
    'schema', coalesce(v_schema, '{}'::jsonb),
    'settings', coalesce(v_settings, '{}'::jsonb),
    'queues',
    jsonb_build_object(
      'pendingDeposits', (select count(*) from public.deposits where status = 'pending'),
      'pendingWithdrawals', (select count(*) from public.withdrawals where status = 'pending'),
      'pendingUsdtWithdrawals', (select count(*) from public.usdt_withdrawals where status = 'pending'),
      'pendingDirectOrders', (select count(*) from public.direct_orders where status = 'pending'),
      'pendingDirectOrdersExpired', (
        select count(*) from public.direct_orders
        where status = 'pending'
          and created_at < now() - interval '10 minutes'
      ),
      'deliveryOutbox', coalesce(v_outbox, '{}'::jsonb)
    ),
    'stock', v_low_stock
  );
end;
$$;

grant execute on function public.admin_record_audit_log(text, text, text, jsonb) to authenticated;
grant execute on function public.admin_ops_health_snapshot(integer) to authenticated;
