-- Durable bot delivery outbox for fulfilled bot direct orders.

create table if not exists public.bot_delivery_outbox (
  id bigint generated by default as identity primary key,
  direct_order_id bigint not null references public.direct_orders(id) on delete cascade,
  user_id bigint not null,
  channel text not null default 'telegram_bot',
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  attempt_count integer not null default 0,
  next_retry_at timestamptz null default now(),
  last_error text null,
  sent_at timestamptz null,
  last_attempt_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint bot_delivery_outbox_direct_order_unique unique (direct_order_id),
  constraint bot_delivery_outbox_channel_check check (channel = 'telegram_bot'),
  constraint bot_delivery_outbox_status_check check (status in ('pending', 'sending', 'sent', 'failed'))
);

create index if not exists idx_bot_delivery_outbox_status_retry
  on public.bot_delivery_outbox (status, next_retry_at, id);

create index if not exists idx_bot_delivery_outbox_user_id
  on public.bot_delivery_outbox (user_id);

create or replace function public.set_bot_delivery_outbox_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_bot_delivery_outbox_updated_at on public.bot_delivery_outbox;
create trigger trg_bot_delivery_outbox_updated_at
before update on public.bot_delivery_outbox
for each row
execute function public.set_bot_delivery_outbox_updated_at();

alter table public.bot_delivery_outbox enable row level security;

drop policy if exists "Admins can read bot delivery outbox" on public.bot_delivery_outbox;
create policy "Admins can read bot delivery outbox"
on public.bot_delivery_outbox
for select
using (public.is_admin());

drop policy if exists "Admins can insert bot delivery outbox" on public.bot_delivery_outbox;
create policy "Admins can insert bot delivery outbox"
on public.bot_delivery_outbox
for insert
with check (public.is_admin());

drop policy if exists "Admins can update bot delivery outbox" on public.bot_delivery_outbox;
create policy "Admins can update bot delivery outbox"
on public.bot_delivery_outbox
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete bot delivery outbox" on public.bot_delivery_outbox;
create policy "Admins can delete bot delivery outbox"
on public.bot_delivery_outbox
for delete
using (public.is_admin());
