-- All-in-one Supabase bootstrap schema for this project.
-- Intended for fresh database setup / migration handoff on a new environment.
-- Source order:
--   1. supabase_schema.sql
--   2. supabase_schema_bot_user_profile_names.sql
--   3. supabase_schema_product_position.sql
--   4. supabase_schema_product_soft_delete.sql
--   5. supabase_schema_bot_product_folders.sql
--   5. supabase_schema_website_dashboard.sql
--   6. supabase_schema_website_product_channel_split.sql
--   7. supabase_schema_bot_manual_finance_actions.sql
--   8. supabase_schema_direct_order_fulfillment.sql
--   9. supabase_schema_bot_balance_purchase_fulfillment.sql
--   10. supabase_schema_bot_admin_analytics.sql
--
-- Note:
-- - Existing split SQL files remain canonical for incremental history.
-- - This file is the convenience bootstrap snapshot assembled from them.

-- ============================================================================
-- BEGIN: supabase_schema.sql
-- ============================================================================

-- Supabase schema for Telegram Shop Bot
-- Run in Supabase SQL editor (service role) before migration

-- Core tables
create table if not exists public.users (
  user_id bigint primary key,
  username text,
  balance bigint default 0,
  balance_usdt numeric default 0,
  language text default 'vi',
  created_at timestamptz
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price bigint not null,
  price_usdt numeric default 0,
  price_tiers jsonb,
  promo_buy_quantity integer default 0,
  promo_bonus_quantity integer default 0,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer default 0,
  website_promo_bonus_quantity integer default 0,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean default true,
  description text,
  format_data text
);

create table if not exists public.format_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  pattern text not null,
  created_at timestamptz default now()
);

create table if not exists public.stock (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  content text not null,
  sold boolean default false
);
create index if not exists stock_product_sold_idx on public.stock (product_id, sold);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id),
  product_id bigint references public.products(id),
  content text,
  price bigint,
  quantity integer default 1,
  order_group text,
  created_at timestamptz
);
create index if not exists orders_user_idx on public.orders (user_id);
create index if not exists orders_product_idx on public.orders (product_id);
create index if not exists orders_created_idx on public.orders (created_at desc);

create table if not exists public.deposits (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id),
  amount bigint,
  code text,
  status text default 'pending',
  created_at timestamptz
);
create index if not exists deposits_status_idx on public.deposits (status);

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id),
  amount bigint,
  momo_phone text,
  status text default 'pending',
  created_at timestamptz
);
create index if not exists withdrawals_status_idx on public.withdrawals (status);

create table if not exists public.settings (
  key text primary key,
  value text
);

create table if not exists public.binance_deposits (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id),
  usdt_amount numeric,
  vnd_amount bigint,
  code text,
  screenshot_file_id text,
  status text default 'pending',
  created_at timestamptz
);
create index if not exists binance_deposits_status_idx on public.binance_deposits (status);

create table if not exists public.usdt_withdrawals (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id),
  usdt_amount numeric,
  wallet_address text,
  network text default 'TRC20',
  status text default 'pending',
  created_at timestamptz
);
create index if not exists usdt_withdrawals_status_idx on public.usdt_withdrawals (status);

create table if not exists public.direct_orders (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(user_id),
  product_id bigint references public.products(id),
  quantity integer default 1,
  bonus_quantity integer default 0,
  unit_price bigint,
  amount bigint,
  code text,
  status text default 'pending',
  created_at timestamptz
);
create index if not exists direct_orders_status_idx on public.direct_orders (status);
create index if not exists direct_orders_code_idx on public.direct_orders (code);

-- Backward-compatible column migrations
alter table public.products add column if not exists price_tiers jsonb;
alter table public.products add column if not exists promo_buy_quantity integer default 0;
alter table public.products add column if not exists promo_bonus_quantity integer default 0;
alter table public.products add column if not exists website_name text;
alter table public.products add column if not exists website_price bigint;
alter table public.products add column if not exists website_price_tiers jsonb;
alter table public.products add column if not exists website_promo_buy_quantity integer default 0;
alter table public.products add column if not exists website_promo_bonus_quantity integer default 0;
alter table public.products add column if not exists website_banner_url text;
alter table public.products add column if not exists website_logo_url text;
alter table public.products add column if not exists website_enabled boolean default true;
alter table public.direct_orders add column if not exists bonus_quantity integer default 0;

create table if not exists public.processed_transactions (
  tx_id text primary key,
  processed_at timestamptz default now()
);

-- Telegram chat logs (for admin dashboard 1-1 chat/history)
create table if not exists public.telegram_messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  message_id bigint not null,
  direction text not null check (direction in ('in', 'out')),
  message_type text not null default 'text',
  text text,
  payload jsonb,
  sent_at timestamptz not null,
  created_at timestamptz default now()
);
create unique index if not exists telegram_messages_chat_message_idx on public.telegram_messages (chat_id, message_id);
create index if not exists telegram_messages_chat_sent_idx on public.telegram_messages (chat_id, sent_at desc);

-- Admin roles
do $$
begin
  if not exists (select 1 from pg_type where typname = 'admin_role') then
    create type public.admin_role as enum ('superadmin', 'admin');
  end if;
end $$;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role public.admin_role not null default 'admin',
  created_at timestamptz default now()
);

-- Helper functions
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid()
  );
$$;

create or replace function public.is_superadmin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = auth.uid() and role = 'superadmin'
  );
$$;

create or replace function public.get_stats()
returns table (users bigint, orders bigint, revenue bigint)
language sql
stable
as $$
  select
    (select count(*) from public.users) as users,
    (select count(*) from public.orders) as orders,
    (select coalesce(sum(price), 0) from public.orders) as revenue;
$$;

create or replace function public.reset_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1), true);
  perform setval(pg_get_serial_sequence('public.stock', 'id'), coalesce((select max(id) from public.stock), 1), true);
  perform setval(pg_get_serial_sequence('public.orders', 'id'), coalesce((select max(id) from public.orders), 1), true);
  perform setval(pg_get_serial_sequence('public.deposits', 'id'), coalesce((select max(id) from public.deposits), 1), true);
  perform setval(pg_get_serial_sequence('public.withdrawals', 'id'), coalesce((select max(id) from public.withdrawals), 1), true);
  perform setval(pg_get_serial_sequence('public.binance_deposits', 'id'), coalesce((select max(id) from public.binance_deposits), 1), true);
  perform setval(pg_get_serial_sequence('public.usdt_withdrawals', 'id'), coalesce((select max(id) from public.usdt_withdrawals), 1), true);
  perform setval(pg_get_serial_sequence('public.format_templates', 'id'), coalesce((select max(id) from public.format_templates), 1), true);
end $$;

-- Fast product queries with stock counts
drop function if exists public.get_products_with_stock();
create or replace function public.get_products_with_stock()
returns table (
  id bigint,
  name text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  stock bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.price,
    p.price_usdt,
    p.price_tiers,
    p.promo_buy_quantity,
    p.promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    p.website_promo_buy_quantity,
    p.website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    p.website_enabled,
    p.description,
    p.format_data,
    coalesce(s.stock, 0) as stock
  from public.products p
  left join (
    select product_id, count(*) as stock
    from public.stock
    where sold = false
    group by product_id
  ) s on s.product_id = p.id
  where (auth.role() = 'service_role' or public.is_admin())
  order by p.id;
$$;

drop function if exists public.get_product_with_stock(bigint);
create or replace function public.get_product_with_stock(p_id bigint)
returns table (
  id bigint,
  name text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  stock bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.price,
    p.price_usdt,
    p.price_tiers,
    p.promo_buy_quantity,
    p.promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    p.website_promo_buy_quantity,
    p.website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    p.website_enabled,
    p.description,
    p.format_data,
    coalesce(s.stock, 0) as stock
  from public.products p
  left join (
    select product_id, count(*) as stock
    from public.stock
    where sold = false
    group by product_id
  ) s on s.product_id = p.id
  where (auth.role() = 'service_role' or public.is_admin())
    and p.id = p_id
  limit 1;
$$;

-- Create deposit + return bank settings in one round-trip
create or replace function public.create_deposit_and_get_bank_settings(
  p_user_id bigint,
  p_amount bigint,
  p_code text
)
returns table (
  bank_name text,
  account_number text,
  account_name text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'not authorized';
  end if;

  insert into public.deposits (user_id, amount, code, created_at)
  values (p_user_id, p_amount, p_code, now());

  return query
  select
    max(value) filter (where key = 'bank_name') as bank_name,
    max(value) filter (where key = 'account_number') as account_number,
    max(value) filter (where key = 'account_name') as account_name
  from public.settings;
end $$;

-- Create direct order + return bank settings in one round-trip
create or replace function public.create_direct_order_and_get_bank_settings(
  p_user_id bigint,
  p_product_id bigint,
  p_quantity integer,
  p_bonus_quantity integer,
  p_unit_price bigint,
  p_amount bigint,
  p_code text
)
returns table (
  bank_name text,
  account_number text,
  account_name text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'not authorized';
  end if;

  insert into public.direct_orders (user_id, product_id, quantity, bonus_quantity, unit_price, amount, code, created_at)
  values (p_user_id, p_product_id, p_quantity, p_bonus_quantity, p_unit_price, p_amount, p_code, now());

  return query
  select
    max(value) filter (where key = 'bank_name') as bank_name,
    max(value) filter (where key = 'account_number') as account_number,
    max(value) filter (where key = 'account_name') as account_name
  from public.settings;
end $$;

-- RLS
alter table public.admin_users enable row level security;
-- NOTE: Keep admin_users policies non-recursive to avoid stack depth errors.
drop policy if exists "Admin can read own" on public.admin_users;
create policy "Admin can read own" on public.admin_users
  for select using (auth.uid() = user_id);

alter table public.users enable row level security;
drop policy if exists "Admins can access users" on public.users;
create policy "Admins can access users" on public.users
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.products enable row level security;
drop policy if exists "Admins can access products" on public.products;
create policy "Admins can access products" on public.products
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.stock enable row level security;
drop policy if exists "Admins can access stock" on public.stock;
create policy "Admins can access stock" on public.stock
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.orders enable row level security;
drop policy if exists "Admins can access orders" on public.orders;
create policy "Admins can access orders" on public.orders
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.deposits enable row level security;
drop policy if exists "Admins can access deposits" on public.deposits;
create policy "Admins can access deposits" on public.deposits
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.withdrawals enable row level security;
drop policy if exists "Admins can access withdrawals" on public.withdrawals;
create policy "Admins can access withdrawals" on public.withdrawals
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.settings enable row level security;
drop policy if exists "Admins can access settings" on public.settings;
create policy "Admins can access settings" on public.settings
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.format_templates enable row level security;
drop policy if exists "Admins can read format templates" on public.format_templates;
create policy "Admins can read format templates" on public.format_templates
  for select using (public.is_admin());
drop policy if exists "Superadmins can write format templates" on public.format_templates;
create policy "Superadmins can write format templates" on public.format_templates
  for all using (public.is_superadmin()) with check (public.is_superadmin());

alter table public.binance_deposits enable row level security;
drop policy if exists "Admins can access binance deposits" on public.binance_deposits;
create policy "Admins can access binance deposits" on public.binance_deposits
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.usdt_withdrawals enable row level security;
drop policy if exists "Admins can access usdt withdrawals" on public.usdt_withdrawals;
create policy "Admins can access usdt withdrawals" on public.usdt_withdrawals
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.processed_transactions enable row level security;
drop policy if exists "Admins can access processed transactions" on public.processed_transactions;
create policy "Admins can access processed transactions" on public.processed_transactions
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.direct_orders enable row level security;
drop policy if exists "Admins can access direct orders" on public.direct_orders;
create policy "Admins can access direct orders" on public.direct_orders
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.telegram_messages enable row level security;
drop policy if exists "Admins can access telegram messages" on public.telegram_messages;
create policy "Admins can access telegram messages" on public.telegram_messages
  for all using (public.is_admin()) with check (public.is_admin());

-- Storage bucket for admin uploads
insert into storage.buckets (id, name, public)
values ('admin-uploads', 'admin-uploads', false)
on conflict (id) do nothing;

-- NOTE: storage.objects is managed by Supabase; RLS is already enabled.
-- Do not alter storage.objects here to avoid permission errors.
drop policy if exists "Admins can access admin uploads" on storage.objects;
create policy "Admins can access admin uploads" on storage.objects
  for all
  using (bucket_id = 'admin-uploads' and public.is_admin())
  with check (bucket_id = 'admin-uploads' and public.is_admin());

-- ============================================================================
-- END: supabase_schema.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_bot_user_profile_names.sql
-- ============================================================================

-- Telegram user profile name fields for Bot admin display.
-- New file on purpose: do not append this into older SQL files.

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS first_name TEXT;

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS last_name TEXT;

COMMENT ON COLUMN public.users.first_name IS
  'Latest Telegram first_name captured from user updates for admin display.';

COMMENT ON COLUMN public.users.last_name IS
  'Latest Telegram last_name captured from user updates for admin display.';

-- ============================================================================
-- END: supabase_schema_bot_user_profile_names.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_product_position.sql
-- ============================================================================

-- Product position sorting migration
-- NOTE: keep this in a separate SQL file (do not append to old schema files)

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS sort_position INTEGER;

CREATE INDEX IF NOT EXISTS idx_products_sort_position
  ON public.products (sort_position, id);

COMMENT ON COLUMN public.products.sort_position IS
  'Manual position for bot product ordering (ascending). NULL means fallback to id order.';

-- ============================================================================
-- END: supabase_schema_product_position.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_product_soft_delete.sql
-- ============================================================================

-- Product soft-delete/hide migration
-- NOTE: keep this in a separate SQL file (do not append to old schema files)

-- 1) Add visibility + soft-delete columns on products
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS is_hidden BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_products_visibility
  ON public.products (is_deleted, is_hidden, id);

-- Defensive cleanup for older rows (if columns were added without NOT NULL/default in prior experiments)
UPDATE public.products
SET is_hidden = COALESCE(is_hidden, FALSE),
    is_deleted = COALESCE(is_deleted, FALSE)
WHERE is_hidden IS NULL OR is_deleted IS NULL;

-- 2) Rebuild stock RPCs so customer-facing product listing ignores hidden/soft-deleted products
DROP FUNCTION IF EXISTS public.get_products_with_stock();
CREATE OR REPLACE FUNCTION public.get_products_with_stock()
RETURNS TABLE (
  id bigint,
  name text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  stock bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    p.id,
    p.name,
    p.price,
    p.price_usdt,
    p.price_tiers,
    p.promo_buy_quantity,
    p.promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    p.website_promo_buy_quantity,
    p.website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    p.website_enabled,
    p.description,
    p.format_data,
    COALESCE(s.stock, 0) AS stock
  FROM public.products p
  LEFT JOIN (
    SELECT product_id, COUNT(*) AS stock
    FROM public.stock
    WHERE sold = FALSE
    GROUP BY product_id
  ) s ON s.product_id = p.id
  WHERE (auth.role() = 'service_role' OR public.is_admin())
    AND COALESCE(p.is_deleted, FALSE) = FALSE
    AND COALESCE(p.is_hidden, FALSE) = FALSE
  ORDER BY p.id;
$$;

DROP FUNCTION IF EXISTS public.get_product_with_stock(bigint);
CREATE OR REPLACE FUNCTION public.get_product_with_stock(p_id bigint)
RETURNS TABLE (
  id bigint,
  name text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  stock bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    p.id,
    p.name,
    p.price,
    p.price_usdt,
    p.price_tiers,
    p.promo_buy_quantity,
    p.promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    p.website_promo_buy_quantity,
    p.website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    p.website_enabled,
    p.description,
    p.format_data,
    COALESCE(s.stock, 0) AS stock
  FROM public.products p
  LEFT JOIN (
    SELECT product_id, COUNT(*) AS stock
    FROM public.stock
    WHERE sold = FALSE
    GROUP BY product_id
  ) s ON s.product_id = p.id
  WHERE (auth.role() = 'service_role' OR public.is_admin())
    AND p.id = p_id
    AND COALESCE(p.is_deleted, FALSE) = FALSE
    AND COALESCE(p.is_hidden, FALSE) = FALSE
  LIMIT 1;
$$;

-- 3) Optional helper function for soft delete (keeps FK-referenced orders intact)
CREATE OR REPLACE FUNCTION public.soft_delete_product(p_product_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT (auth.role() = 'service_role' OR public.is_admin()) THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  UPDATE public.products
  SET
    is_hidden = TRUE,
    is_deleted = TRUE,
    deleted_at = NOW()
  WHERE id = p_product_id;
END;
$$;

-- ============================================================================
-- END: supabase_schema_product_soft_delete.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_bot_product_folders.sql
-- ============================================================================

-- Telegram Bot product folders/categories.
-- New file on purpose: do not append this into older SQL files.

create table if not exists public.bot_product_folders (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_position integer,
  created_at timestamptz not null default now()
);

create unique index if not exists bot_product_folders_name_lower_idx
  on public.bot_product_folders (lower(btrim(name)));

create index if not exists idx_bot_product_folders_sort
  on public.bot_product_folders (sort_position, id);

alter table public.products
  add column if not exists bot_folder_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_bot_folder_id_fkey'
  ) then
    alter table public.products
      add constraint products_bot_folder_id_fkey
      foreign key (bot_folder_id)
      references public.bot_product_folders(id)
      on delete set null;
  end if;
end $$;

create index if not exists idx_products_bot_folder_sort
  on public.products (bot_folder_id, sort_position, id);

alter table public.bot_product_folders enable row level security;
drop policy if exists "Admins can access bot product folders" on public.bot_product_folders;
create policy "Admins can access bot product folders" on public.bot_product_folders
  for all using (public.is_admin()) with check (public.is_admin());

drop function if exists public.get_products_with_stock();
create or replace function public.get_products_with_stock()
returns table (
  id bigint,
  name text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  bot_folder_id bigint,
  stock bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.price,
    p.price_usdt,
    p.price_tiers,
    p.promo_buy_quantity,
    p.promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    p.website_promo_buy_quantity,
    p.website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    p.website_enabled,
    p.description,
    p.format_data,
    p.bot_folder_id,
    coalesce(s.stock, 0) as stock
  from public.products p
  left join (
    select product_id, count(*) as stock
    from public.stock
    where sold = false
    group by product_id
  ) s on s.product_id = p.id
  where (auth.role() = 'service_role' or public.is_admin())
    and coalesce(p.is_deleted, false) = false
    and coalesce(p.is_hidden, false) = false
  order by p.id;
$$;

drop function if exists public.get_product_with_stock(bigint);
create or replace function public.get_product_with_stock(p_id bigint)
returns table (
  id bigint,
  name text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  bot_folder_id bigint,
  stock bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.price,
    p.price_usdt,
    p.price_tiers,
    p.promo_buy_quantity,
    p.promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    p.website_promo_buy_quantity,
    p.website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    p.website_enabled,
    p.description,
    p.format_data,
    p.bot_folder_id,
    coalesce(s.stock, 0) as stock
  from public.products p
  left join (
    select product_id, count(*) as stock
    from public.stock
    where sold = false
    group by product_id
  ) s on s.product_id = p.id
  where (auth.role() = 'service_role' or public.is_admin())
    and p.id = p_id
    and coalesce(p.is_deleted, false) = false
    and coalesce(p.is_hidden, false) = false
  limit 1;
$$;

-- ============================================================================
-- END: supabase_schema_bot_product_folders.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_website_dashboard.sql
-- ============================================================================

-- Website Dashboard split schema
-- NOTE: This file is intentionally separate from existing supabase_schema.sql

-- 1) Product-level website-only description
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS website_description TEXT;

-- 2) Website users (mapped from Supabase Auth users)
CREATE TABLE IF NOT EXISTS public.website_users (
  id BIGSERIAL PRIMARY KEY,
  auth_user_id UUID NOT NULL UNIQUE,
  email TEXT NOT NULL,
  display_name TEXT,
  last_sign_in_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_website_users_email_lower
  ON public.website_users (LOWER(email));

CREATE INDEX IF NOT EXISTS idx_website_users_auth_user_id
  ON public.website_users (auth_user_id);

-- 3) Website direct orders (separate from bot direct_orders)
CREATE TABLE IF NOT EXISTS public.website_direct_orders (
  id BIGSERIAL PRIMARY KEY,
  auth_user_id UUID,
  user_email TEXT,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  quantity INTEGER NOT NULL DEFAULT 1,
  bonus_quantity INTEGER NOT NULL DEFAULT 0,
  unit_price BIGINT NOT NULL DEFAULT 0,
  amount BIGINT NOT NULL DEFAULT 0,
  code TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'failed', 'cancelled')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  confirmed_at TIMESTAMPTZ,
  fulfilled_order_id BIGINT
);

CREATE INDEX IF NOT EXISTS idx_website_direct_orders_auth_user_id
  ON public.website_direct_orders (auth_user_id);

CREATE INDEX IF NOT EXISTS idx_website_direct_orders_status_created_at
  ON public.website_direct_orders (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_website_direct_orders_product_id
  ON public.website_direct_orders (product_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'website_direct_orders_auth_user_id_fkey'
  ) THEN
    ALTER TABLE public.website_direct_orders
      ADD CONSTRAINT website_direct_orders_auth_user_id_fkey
      FOREIGN KEY (auth_user_id)
      REFERENCES public.website_users(auth_user_id)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  END IF;
END $$;

-- 4) Website delivered orders (separate from bot orders)
CREATE TABLE IF NOT EXISTS public.website_orders (
  id BIGSERIAL PRIMARY KEY,
  auth_user_id UUID,
  user_email TEXT,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  content TEXT,
  price BIGINT NOT NULL DEFAULT 0,
  quantity INTEGER NOT NULL DEFAULT 1,
  order_group TEXT,
  source_direct_code TEXT UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_website_orders_auth_user_id
  ON public.website_orders (auth_user_id);

CREATE INDEX IF NOT EXISTS idx_website_orders_created_at
  ON public.website_orders (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_website_orders_product_id
  ON public.website_orders (product_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'website_orders_auth_user_id_fkey'
  ) THEN
    ALTER TABLE public.website_orders
      ADD CONSTRAINT website_orders_auth_user_id_fkey
      FOREIGN KEY (auth_user_id)
      REFERENCES public.website_users(auth_user_id)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  END IF;
END $$;

-- Link website_direct_orders.fulfilled_order_id -> website_orders.id
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'website_direct_orders_fulfilled_order_id_fkey'
  ) THEN
    ALTER TABLE public.website_direct_orders
      ADD CONSTRAINT website_direct_orders_fulfilled_order_id_fkey
      FOREIGN KEY (fulfilled_order_id)
      REFERENCES public.website_orders(id)
      ON UPDATE CASCADE
      ON DELETE SET NULL;
  END IF;
END $$;

-- 5) Generic updated_at trigger helper
CREATE OR REPLACE FUNCTION public.set_row_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_website_users_updated_at ON public.website_users;
CREATE TRIGGER trg_website_users_updated_at
BEFORE UPDATE ON public.website_users
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

DROP TRIGGER IF EXISTS trg_website_direct_orders_updated_at ON public.website_direct_orders;
CREATE TRIGGER trg_website_direct_orders_updated_at
BEFORE UPDATE ON public.website_direct_orders
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

-- 6) Backfill website_users from auth.users
INSERT INTO public.website_users (auth_user_id, email, display_name, last_sign_in_at)
SELECT
  au.id,
  COALESCE(au.email, ''),
  NULLIF(COALESCE(au.raw_user_meta_data ->> 'full_name', au.raw_user_meta_data ->> 'name', ''), ''),
  au.last_sign_in_at
FROM auth.users au
WHERE au.email IS NOT NULL
ON CONFLICT (auth_user_id)
DO UPDATE SET
  email = EXCLUDED.email,
  display_name = COALESCE(EXCLUDED.display_name, public.website_users.display_name),
  last_sign_in_at = COALESCE(EXCLUDED.last_sign_in_at, public.website_users.last_sign_in_at),
  updated_at = NOW();

-- 7) Keep website_users synced with auth.users changes
CREATE OR REPLACE FUNCTION public.sync_website_user_from_auth()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NEW.email IS NULL THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.website_users (auth_user_id, email, display_name, last_sign_in_at)
  VALUES (
    NEW.id,
    NEW.email,
    NULLIF(COALESCE(NEW.raw_user_meta_data ->> 'full_name', NEW.raw_user_meta_data ->> 'name', ''), ''),
    NEW.last_sign_in_at
  )
  ON CONFLICT (auth_user_id)
  DO UPDATE SET
    email = EXCLUDED.email,
    display_name = COALESCE(EXCLUDED.display_name, public.website_users.display_name),
    last_sign_in_at = COALESCE(EXCLUDED.last_sign_in_at, public.website_users.last_sign_in_at),
    updated_at = NOW();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_website_user_from_auth ON auth.users;
CREATE TRIGGER trg_sync_website_user_from_auth
AFTER INSERT OR UPDATE OF email, raw_user_meta_data, last_sign_in_at
ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.sync_website_user_from_auth();

-- ============================================================================
-- END: supabase_schema_website_dashboard.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_website_product_channel_split.sql
-- ============================================================================

-- Website Product channel split:
-- Only stock is shared with Telegram/Bot side.
-- Website merchandising fields are managed independently via website_* columns.

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS website_sort_position INTEGER;

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS website_format_data TEXT;

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS website_deleted BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE public.products
SET
  website_enabled = COALESCE(website_enabled, TRUE),
  website_deleted = COALESCE(website_deleted, FALSE);

-- One-time backfill so Website starts from existing values but can diverge later.
UPDATE public.products
SET website_name = COALESCE(NULLIF(TRIM(website_name), ''), name)
WHERE COALESCE(NULLIF(TRIM(website_name), ''), '') = '';

UPDATE public.products
SET website_price = COALESCE(website_price, price)
WHERE website_price IS NULL;

UPDATE public.products
SET website_description = COALESCE(NULLIF(TRIM(website_description), ''), description)
WHERE COALESCE(NULLIF(TRIM(website_description), ''), '') = ''
  AND COALESCE(NULLIF(TRIM(description), ''), '') <> '';

UPDATE public.products
SET website_format_data = COALESCE(NULLIF(TRIM(website_format_data), ''), format_data)
WHERE COALESCE(NULLIF(TRIM(website_format_data), ''), '') = ''
  AND COALESCE(NULLIF(TRIM(format_data), ''), '') <> '';

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'products'
      AND column_name = 'sort_position'
  ) THEN
    UPDATE public.products
    SET website_sort_position = COALESCE(website_sort_position, sort_position)
    WHERE website_sort_position IS NULL;
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_products_website_channel_visibility
  ON public.products (website_deleted, website_enabled, website_sort_position, id);

COMMENT ON COLUMN public.products.website_sort_position IS
  'Website-only product order position. Smaller values are shown first.';

COMMENT ON COLUMN public.products.website_format_data IS
  'Website-only stock output format template (independent from bot format_data).';

COMMENT ON COLUMN public.products.website_deleted IS
  'Website-only soft delete flag. Does not affect bot-side product visibility.';

-- ============================================================================
-- END: supabase_schema_website_product_channel_split.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_bot_manual_finance_actions.sql
-- ============================================================================

-- Atomic helpers for Bot Dashboard manual financial actions.
-- New file on purpose: do not append this into older SQL files.

create or replace function public.admin_confirm_deposit(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deposit public.deposits%rowtype;
  v_new_balance bigint;
begin
  if not public.is_admin() then
    raise exception 'forbidden';
  end if;

  select * into v_deposit
  from public.deposits
  where id = p_id
  for update;

  if not found then
    raise exception 'deposit_not_found';
  end if;
  if coalesce(v_deposit.status, '') <> 'pending' then
    raise exception 'deposit_not_pending';
  end if;

  update public.users
  set balance = coalesce(balance, 0) + coalesce(v_deposit.amount, 0)
  where user_id = v_deposit.user_id
  returning balance into v_new_balance;

  if v_new_balance is null then
    raise exception 'user_not_found';
  end if;

  update public.deposits
  set status = 'confirmed'
  where id = v_deposit.id;

  return jsonb_build_object(
    'record_id', v_deposit.id,
    'user_id', v_deposit.user_id,
    'status', 'confirmed',
    'amount', v_deposit.amount,
    'new_balance', v_new_balance
  );
end;
$$;

create or replace function public.admin_cancel_deposit(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deposit public.deposits%rowtype;
begin
  if not public.is_admin() then
    raise exception 'forbidden';
  end if;

  select * into v_deposit
  from public.deposits
  where id = p_id
  for update;

  if not found then
    raise exception 'deposit_not_found';
  end if;
  if coalesce(v_deposit.status, '') <> 'pending' then
    raise exception 'deposit_not_pending';
  end if;

  update public.deposits
  set status = 'cancelled'
  where id = v_deposit.id;

  return jsonb_build_object(
    'record_id', v_deposit.id,
    'status', 'cancelled'
  );
end;
$$;

create or replace function public.admin_confirm_withdrawal(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_withdrawal public.withdrawals%rowtype;
  v_balance bigint;
  v_new_balance bigint;
begin
  if not public.is_admin() then
    raise exception 'forbidden';
  end if;

  select * into v_withdrawal
  from public.withdrawals
  where id = p_id
  for update;

  if not found then
    raise exception 'withdrawal_not_found';
  end if;
  if coalesce(v_withdrawal.status, '') <> 'pending' then
    raise exception 'withdrawal_not_pending';
  end if;

  select balance into v_balance
  from public.users
  where user_id = v_withdrawal.user_id
  for update;

  if not found then
    raise exception 'user_not_found';
  end if;
  if coalesce(v_balance, 0) < coalesce(v_withdrawal.amount, 0) then
    raise exception 'insufficient_balance';
  end if;

  update public.users
  set balance = coalesce(balance, 0) - coalesce(v_withdrawal.amount, 0)
  where user_id = v_withdrawal.user_id
  returning balance into v_new_balance;

  update public.withdrawals
  set status = 'confirmed'
  where id = v_withdrawal.id;

  return jsonb_build_object(
    'record_id', v_withdrawal.id,
    'user_id', v_withdrawal.user_id,
    'status', 'confirmed',
    'amount', v_withdrawal.amount,
    'new_balance', v_new_balance
  );
end;
$$;

create or replace function public.admin_cancel_withdrawal(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_withdrawal public.withdrawals%rowtype;
begin
  if not public.is_admin() then
    raise exception 'forbidden';
  end if;

  select * into v_withdrawal
  from public.withdrawals
  where id = p_id
  for update;

  if not found then
    raise exception 'withdrawal_not_found';
  end if;
  if coalesce(v_withdrawal.status, '') <> 'pending' then
    raise exception 'withdrawal_not_pending';
  end if;

  update public.withdrawals
  set status = 'cancelled'
  where id = v_withdrawal.id;

  return jsonb_build_object(
    'record_id', v_withdrawal.id,
    'status', 'cancelled'
  );
end;
$$;

create or replace function public.admin_confirm_binance_deposit(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deposit public.binance_deposits%rowtype;
  v_new_balance numeric;
begin
  if not public.is_admin() then
    raise exception 'forbidden';
  end if;

  select * into v_deposit
  from public.binance_deposits
  where id = p_id
  for update;

  if not found then
    raise exception 'binance_deposit_not_found';
  end if;
  if coalesce(v_deposit.status, '') <> 'pending' then
    raise exception 'binance_deposit_not_pending';
  end if;

  update public.users
  set balance_usdt = coalesce(balance_usdt, 0) + coalesce(v_deposit.usdt_amount, 0)
  where user_id = v_deposit.user_id
  returning balance_usdt into v_new_balance;

  if v_new_balance is null then
    raise exception 'user_not_found';
  end if;

  update public.binance_deposits
  set status = 'confirmed'
  where id = v_deposit.id;

  return jsonb_build_object(
    'record_id', v_deposit.id,
    'user_id', v_deposit.user_id,
    'status', 'confirmed',
    'amount', v_deposit.usdt_amount,
    'new_balance', v_new_balance
  );
end;
$$;

create or replace function public.admin_cancel_binance_deposit(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deposit public.binance_deposits%rowtype;
begin
  if not public.is_admin() then
    raise exception 'forbidden';
  end if;

  select * into v_deposit
  from public.binance_deposits
  where id = p_id
  for update;

  if not found then
    raise exception 'binance_deposit_not_found';
  end if;
  if coalesce(v_deposit.status, '') <> 'pending' then
    raise exception 'binance_deposit_not_pending';
  end if;

  update public.binance_deposits
  set status = 'cancelled'
  where id = v_deposit.id;

  return jsonb_build_object(
    'record_id', v_deposit.id,
    'status', 'cancelled'
  );
end;
$$;

create or replace function public.admin_confirm_usdt_withdrawal(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_withdrawal public.usdt_withdrawals%rowtype;
  v_balance numeric;
  v_new_balance numeric;
begin
  if not public.is_admin() then
    raise exception 'forbidden';
  end if;

  select * into v_withdrawal
  from public.usdt_withdrawals
  where id = p_id
  for update;

  if not found then
    raise exception 'usdt_withdrawal_not_found';
  end if;
  if coalesce(v_withdrawal.status, '') <> 'pending' then
    raise exception 'usdt_withdrawal_not_pending';
  end if;

  select balance_usdt into v_balance
  from public.users
  where user_id = v_withdrawal.user_id
  for update;

  if not found then
    raise exception 'user_not_found';
  end if;
  if coalesce(v_balance, 0) < coalesce(v_withdrawal.usdt_amount, 0) then
    raise exception 'insufficient_usdt_balance';
  end if;

  update public.users
  set balance_usdt = coalesce(balance_usdt, 0) - coalesce(v_withdrawal.usdt_amount, 0)
  where user_id = v_withdrawal.user_id
  returning balance_usdt into v_new_balance;

  update public.usdt_withdrawals
  set status = 'confirmed'
  where id = v_withdrawal.id;

  return jsonb_build_object(
    'record_id', v_withdrawal.id,
    'user_id', v_withdrawal.user_id,
    'status', 'confirmed',
    'amount', v_withdrawal.usdt_amount,
    'new_balance', v_new_balance
  );
end;
$$;

create or replace function public.admin_cancel_usdt_withdrawal(p_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_withdrawal public.usdt_withdrawals%rowtype;
begin
  if not public.is_admin() then
    raise exception 'forbidden';
  end if;

  select * into v_withdrawal
  from public.usdt_withdrawals
  where id = p_id
  for update;

  if not found then
    raise exception 'usdt_withdrawal_not_found';
  end if;
  if coalesce(v_withdrawal.status, '') <> 'pending' then
    raise exception 'usdt_withdrawal_not_pending';
  end if;

  update public.usdt_withdrawals
  set status = 'cancelled'
  where id = v_withdrawal.id;

  return jsonb_build_object(
    'record_id', v_withdrawal.id,
    'status', 'cancelled'
  );
end;
$$;

grant execute on function public.admin_confirm_deposit(bigint) to authenticated;
grant execute on function public.admin_cancel_deposit(bigint) to authenticated;
grant execute on function public.admin_confirm_withdrawal(bigint) to authenticated;
grant execute on function public.admin_cancel_withdrawal(bigint) to authenticated;
grant execute on function public.admin_confirm_binance_deposit(bigint) to authenticated;
grant execute on function public.admin_cancel_binance_deposit(bigint) to authenticated;
grant execute on function public.admin_confirm_usdt_withdrawal(bigint) to authenticated;
grant execute on function public.admin_cancel_usdt_withdrawal(bigint) to authenticated;

-- ============================================================================
-- END: supabase_schema_bot_manual_finance_actions.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_direct_order_fulfillment.sql
-- ============================================================================

-- Shared direct-order fulfillment helpers for Bot + Website.
-- New file on purpose: do not append this into older SQL files.

create or replace function public.fulfill_bot_direct_order(
  p_direct_order_id bigint,
  p_order_group text default null,
  p_expire_minutes integer default 10
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.direct_orders%rowtype;
  v_product_name text;
  v_description text;
  v_format_data text;
  v_deliver_quantity integer;
  v_order_group text;
  v_stock_ids bigint[];
  v_items jsonb;
  v_stock_count integer;
  v_created_order_id bigint;
  v_total_price bigint;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  select *
  into v_order
  from public.direct_orders
  where id = p_direct_order_id
  for update;

  if not found then
    raise exception 'direct_order_not_found';
  end if;

  if coalesce(v_order.status, '') <> 'pending' then
    raise exception 'direct_order_not_pending';
  end if;

  if v_order.created_at is not null
    and v_order.created_at <= now() - make_interval(mins => greatest(1, coalesce(p_expire_minutes, 10)))
  then
    update public.direct_orders
    set status = 'cancelled'
    where id = v_order.id;

    raise exception 'direct_order_expired';
  end if;

  select
    p.name,
    p.description,
    p.format_data
  into
    v_product_name,
    v_description,
    v_format_data
  from public.products p
  where p.id = v_order.product_id;

  v_deliver_quantity := greatest(1, coalesce(v_order.quantity, 0) + greatest(0, coalesce(v_order.bonus_quantity, 0)));

  with locked_stock as (
    select s.id, s.content
    from public.stock s
    where s.product_id = v_order.product_id
      and s.sold = false
    order by s.id
    for update skip locked
    limit v_deliver_quantity
  )
  select
    array_agg(ls.id order by ls.id),
    coalesce(jsonb_agg(ls.content order by ls.id), '[]'::jsonb),
    count(*)
  into
    v_stock_ids,
    v_items,
    v_stock_count
  from locked_stock ls;

  if coalesce(v_stock_count, 0) < v_deliver_quantity then
    update public.direct_orders
    set status = 'failed'
    where id = v_order.id;

    raise exception 'not_enough_stock';
  end if;

  update public.stock
  set sold = true
  where id = any(v_stock_ids);

  v_order_group := coalesce(
    nullif(btrim(p_order_group), ''),
    'PAY' || v_order.user_id::text || to_char(now(), 'YYYYMMDDHH24MISS')
  );
  v_total_price := coalesce(v_order.amount, coalesce(v_order.unit_price, 0) * greatest(1, coalesce(v_order.quantity, 0)));

  insert into public.orders (
    user_id,
    product_id,
    content,
    price,
    quantity,
    order_group,
    created_at
  )
  values (
    v_order.user_id,
    v_order.product_id,
    v_items::text,
    v_total_price,
    v_deliver_quantity,
    v_order_group,
    now()
  )
  returning id into v_created_order_id;

  update public.direct_orders
  set status = 'confirmed'
  where id = v_order.id;

  return jsonb_build_object(
    'direct_order_id', v_order.id,
    'order_id', v_created_order_id,
    'user_id', v_order.user_id,
    'product_id', v_order.product_id,
    'product_name', coalesce(nullif(btrim(v_product_name), ''), '#' || v_order.product_id::text),
    'description', coalesce(v_description, ''),
    'format_data', coalesce(v_format_data, ''),
    'quantity', coalesce(v_order.quantity, 1),
    'bonus_quantity', coalesce(v_order.bonus_quantity, 0),
    'delivered_quantity', v_deliver_quantity,
    'unit_price', coalesce(v_order.unit_price, 0),
    'amount', v_total_price,
    'code', coalesce(v_order.code, ''),
    'order_group', v_order_group,
    'items', coalesce(v_items, '[]'::jsonb)
  );
end;
$$;

create or replace function public.fulfill_website_direct_order(
  p_website_direct_order_id bigint,
  p_order_group text default null,
  p_expire_minutes integer default 10
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.website_direct_orders%rowtype;
  v_mirror public.direct_orders%rowtype;
  v_product_name text;
  v_deliver_quantity integer;
  v_order_group text;
  v_stock_ids bigint[];
  v_items jsonb;
  v_stock_count integer;
  v_created_order_id bigint;
  v_total_price bigint;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  select *
  into v_order
  from public.website_direct_orders
  where id = p_website_direct_order_id
  for update;

  if not found then
    raise exception 'website_direct_order_not_found';
  end if;

  if coalesce(v_order.status, '') <> 'pending' then
    raise exception 'website_direct_order_not_pending';
  end if;

  if v_order.created_at is not null
    and v_order.created_at <= now() - make_interval(mins => greatest(1, coalesce(p_expire_minutes, 10)))
  then
    update public.website_direct_orders
    set status = 'cancelled',
        updated_at = now()
    where id = v_order.id;

    update public.direct_orders
    set status = 'cancelled'
    where code = v_order.code
      and status = 'pending';

    raise exception 'website_direct_order_expired';
  end if;

  select *
  into v_mirror
  from public.direct_orders
  where code = v_order.code
  order by id desc
  limit 1
  for update;

  if not found then
    raise exception 'mirror_direct_order_not_found';
  end if;

  if coalesce(v_mirror.status, '') <> 'pending' then
    raise exception 'mirror_direct_order_not_pending';
  end if;

  select
    coalesce(nullif(btrim(p.website_name), ''), p.name)
  into
    v_product_name
  from public.products p
  where p.id = v_order.product_id;

  v_deliver_quantity := greatest(1, coalesce(v_order.quantity, 0) + greatest(0, coalesce(v_order.bonus_quantity, 0)));

  with locked_stock as (
    select s.id, s.content
    from public.stock s
    where s.product_id = v_order.product_id
      and s.sold = false
    order by s.id
    for update skip locked
    limit v_deliver_quantity
  )
  select
    array_agg(ls.id order by ls.id),
    coalesce(jsonb_agg(ls.content order by ls.id), '[]'::jsonb),
    count(*)
  into
    v_stock_ids,
    v_items,
    v_stock_count
  from locked_stock ls;

  if coalesce(v_stock_count, 0) < v_deliver_quantity then
    update public.website_direct_orders
    set status = 'failed',
        updated_at = now()
    where id = v_order.id;

    update public.direct_orders
    set status = 'failed'
    where id = v_mirror.id;

    raise exception 'not_enough_stock';
  end if;

  update public.stock
  set sold = true
  where id = any(v_stock_ids);

  v_order_group := coalesce(
    nullif(btrim(p_order_group), ''),
    'WEB' || to_char(now(), 'YYYYMMDDHH24MISS')
  );
  v_total_price := coalesce(v_order.amount, coalesce(v_order.unit_price, 0) * greatest(1, coalesce(v_order.quantity, 0)));

  insert into public.website_orders (
    auth_user_id,
    user_email,
    product_id,
    content,
    price,
    quantity,
    order_group,
    source_direct_code,
    created_at
  )
  values (
    v_order.auth_user_id,
    v_order.user_email,
    v_order.product_id,
    v_items::text,
    v_total_price,
    v_deliver_quantity,
    v_order_group,
    v_order.code,
    now()
  )
  returning id into v_created_order_id;

  update public.website_direct_orders
  set status = 'confirmed',
      confirmed_at = now(),
      updated_at = now(),
      fulfilled_order_id = v_created_order_id
  where id = v_order.id;

  update public.direct_orders
  set status = 'confirmed'
  where id = v_mirror.id;

  return jsonb_build_object(
    'website_direct_order_id', v_order.id,
    'direct_order_id', v_mirror.id,
    'website_order_id', v_created_order_id,
    'auth_user_id', coalesce(v_order.auth_user_id, ''),
    'user_email', coalesce(v_order.user_email, ''),
    'product_id', v_order.product_id,
    'product_name', coalesce(nullif(btrim(v_product_name), ''), '#' || v_order.product_id::text),
    'quantity', coalesce(v_order.quantity, 1),
    'bonus_quantity', coalesce(v_order.bonus_quantity, 0),
    'delivered_quantity', v_deliver_quantity,
    'unit_price', coalesce(v_order.unit_price, 0),
    'amount', v_total_price,
    'code', coalesce(v_order.code, ''),
    'order_group', v_order_group,
    'items', coalesce(v_items, '[]'::jsonb)
  );
end;
$$;

grant execute on function public.fulfill_bot_direct_order(bigint, text, integer) to authenticated;
grant execute on function public.fulfill_website_direct_order(bigint, text, integer) to authenticated;

-- ============================================================================
-- END: supabase_schema_direct_order_fulfillment.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_bot_balance_purchase_fulfillment.sql
-- ============================================================================

-- Atomic helper for Bot instant balance / USDT purchases.
-- New file on purpose: do not append this into older SQL files.

create or replace function public.fulfill_bot_balance_purchase(
  p_user_id bigint,
  p_product_id bigint,
  p_quantity integer,
  p_bonus_quantity integer default 0,
  p_order_price_per_item bigint default 0,
  p_order_total_price bigint default 0,
  p_charge_balance bigint default 0,
  p_charge_balance_usdt numeric default 0,
  p_order_group text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_product public.products%rowtype;
  v_balance bigint;
  v_balance_usdt numeric;
  v_required_stock integer;
  v_stock_ids bigint[];
  v_items jsonb;
  v_stock_count integer;
  v_order_group text;
  v_created_order_id bigint;
  v_unit_price bigint;
  v_total_price bigint;
  v_new_balance bigint;
  v_new_balance_usdt numeric;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  insert into public.users (user_id, created_at)
  values (p_user_id, now())
  on conflict (user_id) do nothing;

  select *
  into v_product
  from public.products
  where id = p_product_id
  for update;

  if not found then
    raise exception 'product_not_found';
  end if;

  select
    coalesce(u.balance, 0),
    coalesce(u.balance_usdt, 0)
  into
    v_balance,
    v_balance_usdt
  from public.users u
  where u.user_id = p_user_id
  for update;

  if not found then
    raise exception 'user_not_found';
  end if;

  if greatest(0, coalesce(p_charge_balance, 0)) > v_balance then
    raise exception 'insufficient_balance';
  end if;

  if greatest(0, coalesce(p_charge_balance_usdt, 0)) > v_balance_usdt then
    raise exception 'insufficient_usdt_balance';
  end if;

  v_required_stock := greatest(1, coalesce(p_quantity, 0) + greatest(0, coalesce(p_bonus_quantity, 0)));

  with locked_stock as (
    select s.id, s.content
    from public.stock s
    where s.product_id = p_product_id
      and s.sold = false
    order by s.id
    for update skip locked
    limit v_required_stock
  )
  select
    array_agg(ls.id order by ls.id),
    coalesce(jsonb_agg(ls.content order by ls.id), '[]'::jsonb),
    count(*)
  into
    v_stock_ids,
    v_items,
    v_stock_count
  from locked_stock ls;

  if coalesce(v_stock_count, 0) < v_required_stock then
    raise exception 'not_enough_stock';
  end if;

  update public.stock
  set sold = true
  where id = any(v_stock_ids);

  update public.users
  set balance = coalesce(balance, 0) - greatest(0, coalesce(p_charge_balance, 0)),
      balance_usdt = coalesce(balance_usdt, 0) - greatest(0, coalesce(p_charge_balance_usdt, 0))
  where user_id = p_user_id
  returning balance, balance_usdt into v_new_balance, v_new_balance_usdt;

  v_order_group := coalesce(
    nullif(btrim(p_order_group), ''),
    'ORD' || p_user_id::text || to_char(now(), 'YYYYMMDDHH24MISS')
  );
  v_unit_price := greatest(0, coalesce(p_order_price_per_item, 0));
  v_total_price := greatest(
    0,
    coalesce(
      p_order_total_price,
      v_unit_price * greatest(1, coalesce(p_quantity, 0))
    )
  );

  insert into public.orders (
    user_id,
    product_id,
    content,
    price,
    quantity,
    order_group,
    created_at
  )
  values (
    p_user_id,
    p_product_id,
    v_items::text,
    v_total_price,
    v_required_stock,
    v_order_group,
    now()
  )
  returning id into v_created_order_id;

  return jsonb_build_object(
    'order_id', v_created_order_id,
    'user_id', p_user_id,
    'product_id', p_product_id,
    'product_name', coalesce(nullif(btrim(v_product.name), ''), '#' || p_product_id::text),
    'description', coalesce(v_product.description, ''),
    'format_data', coalesce(v_product.format_data, ''),
    'quantity', greatest(1, coalesce(p_quantity, 0)),
    'bonus_quantity', greatest(0, coalesce(p_bonus_quantity, 0)),
    'delivered_quantity', v_required_stock,
    'order_group', v_order_group,
    'items', coalesce(v_items, '[]'::jsonb),
    'order_total_price', v_total_price,
    'charged_balance', greatest(0, coalesce(p_charge_balance, 0)),
    'charged_balance_usdt', greatest(0, coalesce(p_charge_balance_usdt, 0)),
    'new_balance', coalesce(v_new_balance, 0),
    'new_balance_usdt', coalesce(v_new_balance_usdt, 0)
  );
end;
$$;

grant execute on function public.fulfill_bot_balance_purchase(
  bigint,
  bigint,
  integer,
  integer,
  bigint,
  bigint,
  bigint,
  numeric,
  text
) to authenticated;

-- ============================================================================
-- END: supabase_schema_bot_balance_purchase_fulfillment.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_bot_admin_analytics.sql
-- ============================================================================

-- Bot admin analytics snapshot helpers.
-- New file on purpose: do not append this into older SQL files.

create or replace function public.admin_bot_dashboard_snapshot(
  p_recent_limit integer default 6
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recent_limit integer := greatest(1, least(coalesce(p_recent_limit, 6), 50));
  v_latest_orders jsonb;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', recent.id,
          'user_id', recent.user_id,
          'username', recent.username,
          'product_id', recent.product_id,
          'product_name', recent.product_name,
          'price', recent.price,
          'quantity', recent.quantity,
          'created_at', recent.created_at
        )
        order by recent.created_at desc nulls last, recent.id desc
      ),
      '[]'::jsonb
    )
  into v_latest_orders
  from (
    select
      o.id,
      o.user_id,
      u.username,
      o.product_id,
      coalesce(nullif(btrim(p.name), ''), '#' || coalesce(o.product_id::text, '-')) as product_name,
      coalesce(o.price, 0) as price,
      coalesce(o.quantity, 0) as quantity,
      o.created_at
    from public.orders o
    left join public.users u on u.user_id = o.user_id
    left join public.products p on p.id = o.product_id
    order by o.created_at desc nulls last, o.id desc
    limit v_recent_limit
  ) recent;

  return jsonb_build_object(
    'stats',
    jsonb_build_object(
      'users', (select count(*)::bigint from public.users),
      'orders', (select count(*)::bigint from public.orders),
      'revenue', (select coalesce(sum(price), 0)::bigint from public.orders)
    ),
    'pendingDeposits', (select count(*)::bigint from public.deposits where status = 'pending'),
    'pendingWithdrawals', (select count(*)::bigint from public.withdrawals where status = 'pending'),
    'orders', coalesce(v_latest_orders, '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_bot_reports_snapshot(
  p_tz text default 'Asia/Ho_Chi_Minh',
  p_expire_minutes integer default 10
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tz text := coalesce(nullif(btrim(p_tz), ''), 'Asia/Ho_Chi_Minh');
  v_now_local timestamp := timezone(v_tz, now());
  v_today_start_local timestamp := date_trunc('day', v_now_local);
  v_yesterday_start_local timestamp := v_today_start_local - interval '1 day';
  v_start7_utc timestamptz := now() - interval '7 day';
  v_start_prev7_utc timestamptz := now() - interval '14 day';
  v_start30_utc timestamptz := now() - interval '30 day';
  v_pending_expired_before timestamptz := now() - make_interval(mins => greatest(1, coalesce(p_expire_minutes, 10)));
  v_revenue jsonb;
  v_order_ops jsonb;
  v_direct_order_stats jsonb;
  v_daily_trend jsonb;
  v_top_products jsonb;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  select
    jsonb_build_object(
      'today', coalesce(sum(coalesce(o.price, 0)) filter (where timezone(v_tz, o.created_at) >= v_today_start_local), 0)::bigint,
      'yesterday', coalesce(sum(coalesce(o.price, 0)) filter (
        where timezone(v_tz, o.created_at) >= v_yesterday_start_local
          and timezone(v_tz, o.created_at) < v_today_start_local
      ), 0)::bigint,
      'last7', coalesce(sum(coalesce(o.price, 0)) filter (where o.created_at >= v_start7_utc), 0)::bigint,
      'previous7', coalesce(sum(coalesce(o.price, 0)) filter (
        where o.created_at >= v_start_prev7_utc
          and o.created_at < v_start7_utc
      ), 0)::bigint,
      'last30', coalesce(sum(coalesce(o.price, 0)) filter (where o.created_at >= v_start30_utc), 0)::bigint
    ),
    jsonb_build_object(
      'ordersToday', count(*) filter (where timezone(v_tz, o.created_at) >= v_today_start_local),
      'ordersLast7', count(*) filter (where o.created_at >= v_start7_utc),
      'ordersLast30', count(*) filter (where o.created_at >= v_start30_utc),
      'averageOrderValue30',
        coalesce(
          coalesce(sum(coalesce(o.price, 0)) filter (where o.created_at >= v_start30_utc), 0)::numeric
          / nullif(count(*) filter (where o.created_at >= v_start30_utc), 0),
          0
        ),
      'averageQuantity30',
        coalesce(
          coalesce(sum(coalesce(o.quantity, 0)) filter (where o.created_at >= v_start30_utc), 0)::numeric
          / nullif(count(*) filter (where o.created_at >= v_start30_utc), 0),
          0
        )
    )
  into
    v_revenue,
    v_order_ops
  from public.orders o;

  select jsonb_build_object(
    'total', total_count,
    'confirmed', confirmed_count,
    'failed', failed_count,
    'cancelled', cancelled_count,
    'pending', pending_count,
    'pendingExpired', pending_expired_count,
    'confirmedRate',
      case
        when processed_count > 0 then (confirmed_count::numeric / processed_count::numeric) * 100
        else 0
      end,
    'failedRate',
      case
        when processed_count > 0 then ((failed_count + cancelled_count)::numeric / processed_count::numeric) * 100
        else 0
      end
  )
  into v_direct_order_stats
  from (
    select
      count(*)::bigint as total_count,
      count(*) filter (where status = 'confirmed')::bigint as confirmed_count,
      count(*) filter (where status = 'failed')::bigint as failed_count,
      count(*) filter (where status = 'cancelled')::bigint as cancelled_count,
      count(*) filter (where status = 'pending')::bigint as pending_count,
      count(*) filter (where status = 'pending' and created_at < v_pending_expired_before)::bigint as pending_expired_count,
      (
        count(*) filter (where status = 'confirmed')
        + count(*) filter (where status = 'failed')
        + count(*) filter (where status = 'cancelled')
      )::bigint as processed_count
    from public.direct_orders
  ) stats;

  with trend_seed as (
    select generate_series(
      v_today_start_local - interval '6 day',
      v_today_start_local,
      interval '1 day'
    ) as day_start
  ),
  trend_rows as (
    select
      ts.day_start::date as day_date,
      to_char(ts.day_start, 'DD/MM') as label,
      count(o.id)::bigint as orders,
      coalesce(sum(coalesce(o.price, 0)), 0)::bigint as revenue
    from trend_seed ts
    left join public.orders o
      on timezone(v_tz, o.created_at) >= ts.day_start
     and timezone(v_tz, o.created_at) < ts.day_start + interval '1 day'
    group by ts.day_start
    order by ts.day_start
  )
  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'dateKey', to_char(tr.day_date, 'YYYY-MM-DD'),
          'label', tr.label,
          'orders', tr.orders,
          'revenue', tr.revenue
        )
        order by tr.day_date
      ),
      '[]'::jsonb
    )
  into v_daily_trend
  from trend_rows tr;

  with top_rows as (
    select
      o.product_id,
      coalesce(nullif(btrim(p.name), ''), '#' || coalesce(o.product_id::text, '-')) as product_name,
      count(*)::bigint as orders,
      coalesce(sum(coalesce(o.quantity, 0)), 0)::bigint as quantity,
      coalesce(sum(coalesce(o.price, 0)), 0)::bigint as revenue
    from public.orders o
    left join public.products p on p.id = o.product_id
    where o.created_at >= v_start30_utc
    group by o.product_id, p.name
    order by revenue desc, quantity desc, orders desc
    limit 8
  )
  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'productId', coalesce(tr.product_id::text, '-'),
          'productName', tr.product_name,
          'orders', tr.orders,
          'quantity', tr.quantity,
          'revenue', tr.revenue
        )
        order by tr.revenue desc, tr.quantity desc, tr.orders desc
      ),
      '[]'::jsonb
    )
  into v_top_products
  from top_rows tr;

  return jsonb_build_object(
    'revenue', coalesce(v_revenue, '{}'::jsonb),
    'orderOps', coalesce(v_order_ops, '{}'::jsonb),
    'directOrderStats', coalesce(v_direct_order_stats, '{}'::jsonb),
    'dailyTrend', coalesce(v_daily_trend, '[]'::jsonb),
    'topProducts', coalesce(v_top_products, '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_bot_users_snapshot(
  p_limit integer default 200
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit integer := greatest(1, least(coalesce(p_limit, 200), 1000));
  v_users jsonb;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  with base_users as (
    select
      u.user_id,
      u.username,
      coalesce(u.balance, 0) as balance,
      coalesce(u.balance_usdt, 0) as balance_usdt,
      u.language,
      u.created_at
    from public.users u
    order by u.created_at desc nulls last, u.user_id desc
    limit v_limit
  ),
  order_stats as (
    select
      o.user_id,
      count(*)::bigint as order_count,
      coalesce(sum(coalesce(o.price, 0)), 0)::bigint as total_paid
    from public.orders o
    join base_users bu on bu.user_id = o.user_id
    group by o.user_id
  )
  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'user_id', bu.user_id,
          'username', bu.username,
          'balance', bu.balance,
          'balance_usdt', bu.balance_usdt,
          'language', bu.language,
          'created_at', bu.created_at,
          'order_count', coalesce(os.order_count, 0),
          'total_paid', coalesce(os.total_paid, 0)
        )
        order by bu.created_at desc nulls last, bu.user_id desc
      ),
      '[]'::jsonb
    )
  into v_users
  from base_users bu
  left join order_stats os on os.user_id = bu.user_id;

  return jsonb_build_object(
    'users', coalesce(v_users, '[]'::jsonb)
  );
end;
$$;

grant execute on function public.admin_bot_dashboard_snapshot(integer) to authenticated;
grant execute on function public.admin_bot_reports_snapshot(text, integer) to authenticated;
grant execute on function public.admin_bot_users_snapshot(integer) to authenticated;

-- ============================================================================
-- END: supabase_schema_bot_admin_analytics.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_bot_admin_analytics_perf.sql
-- ============================================================================

alter table public.users
  add column if not exists first_name text;

alter table public.users
  add column if not exists last_name text;

create index if not exists users_created_user_idx
  on public.users (created_at desc, user_id desc);

create or replace function public.admin_bot_dashboard_snapshot(
  p_recent_limit integer default 6
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recent_limit integer := greatest(1, least(coalesce(p_recent_limit, 6), 50));
  v_latest_orders jsonb;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'id', recent.id,
          'user_id', recent.user_id,
          'username', recent.username,
          'display_name', recent.display_name,
          'product_id', recent.product_id,
          'product_name', recent.product_name,
          'price', recent.price,
          'quantity', recent.quantity,
          'created_at', recent.created_at
        )
        order by recent.created_at desc nulls last, recent.id desc
      ),
      '[]'::jsonb
    )
  into v_latest_orders
  from (
    select
      o.id,
      o.user_id,
      u.username,
      nullif(
        trim(
          concat_ws(
            ' ',
            nullif(btrim(u.first_name), ''),
            nullif(btrim(u.last_name), '')
          )
        ),
        ''
      ) as display_name,
      o.product_id,
      coalesce(nullif(btrim(p.name), ''), '#' || coalesce(o.product_id::text, '-')) as product_name,
      coalesce(o.price, 0) as price,
      coalesce(o.quantity, 0) as quantity,
      o.created_at
    from public.orders o
    left join public.users u on u.user_id = o.user_id
    left join public.products p on p.id = o.product_id
    order by o.created_at desc nulls last, o.id desc
    limit v_recent_limit
  ) recent;

  return jsonb_build_object(
    'stats',
    jsonb_build_object(
      'users', (select count(*)::bigint from public.users),
      'orders', (select count(*)::bigint from public.orders),
      'revenue', (select coalesce(sum(price), 0)::bigint from public.orders)
    ),
    'pendingDeposits', (select count(*)::bigint from public.deposits where status = 'pending'),
    'pendingWithdrawals', (select count(*)::bigint from public.withdrawals where status = 'pending'),
    'orders', coalesce(v_latest_orders, '[]'::jsonb)
  );
end;
$$;

create or replace function public.admin_bot_users_snapshot_page(
  p_page integer default 1,
  p_page_size integer default 50,
  p_search text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_page integer := greatest(1, coalesce(p_page, 1));
  v_page_size integer := greatest(1, least(coalesce(p_page_size, 50), 200));
  v_search text := lower(coalesce(nullif(btrim(p_search), ''), ''));
  v_search_no_at text := regexp_replace(v_search, '^@+', '');
  v_total_count bigint := 0;
  v_total_pages integer := 1;
  v_safe_page integer := 1;
  v_users jsonb;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  with filtered_users as (
    select u.user_id
    from public.users u
    where
      v_search = ''
      or u.user_id::text ilike '%' || v_search_no_at || '%'
      or coalesce(lower(u.username), '') like '%' || v_search || '%'
      or coalesce(lower(u.username), '') like '%' || v_search_no_at || '%'
      or coalesce(
        lower(
          trim(
            concat_ws(
              ' ',
              nullif(btrim(u.first_name), ''),
              nullif(btrim(u.last_name), '')
            )
          )
        ),
        ''
      ) like '%' || v_search || '%'
  )
  select count(*)::bigint into v_total_count
  from filtered_users;

  v_total_pages := greatest(1, ceiling(v_total_count::numeric / v_page_size)::integer);
  v_safe_page := least(v_page, v_total_pages);

  with filtered_users as (
    select
      u.user_id,
      u.username,
      u.first_name,
      u.last_name,
      coalesce(u.balance, 0) as balance,
      coalesce(u.balance_usdt, 0) as balance_usdt,
      u.language,
      u.created_at
    from public.users u
    where
      v_search = ''
      or u.user_id::text ilike '%' || v_search_no_at || '%'
      or coalesce(lower(u.username), '') like '%' || v_search || '%'
      or coalesce(lower(u.username), '') like '%' || v_search_no_at || '%'
      or coalesce(
        lower(
          trim(
            concat_ws(
              ' ',
              nullif(btrim(u.first_name), ''),
              nullif(btrim(u.last_name), '')
            )
          )
        ),
        ''
      ) like '%' || v_search || '%'
  ),
  paged_users as (
    select *
    from filtered_users
    order by created_at desc nulls last, user_id desc
    offset (v_safe_page - 1) * v_page_size
    limit v_page_size
  ),
  order_stats as (
    select
      o.user_id,
      count(*)::bigint as order_count,
      coalesce(sum(coalesce(o.price, 0)), 0)::bigint as total_paid
    from public.orders o
    join paged_users pu on pu.user_id = o.user_id
    group by o.user_id
  )
  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'user_id', pu.user_id,
          'username', pu.username,
          'display_name',
            nullif(
              trim(
                concat_ws(
                  ' ',
                  nullif(btrim(pu.first_name), ''),
                  nullif(btrim(pu.last_name), '')
                )
              ),
              ''
            ),
          'balance', pu.balance,
          'balance_usdt', pu.balance_usdt,
          'language', pu.language,
          'created_at', pu.created_at,
          'order_count', coalesce(os.order_count, 0),
          'total_paid', coalesce(os.total_paid, 0)
        )
        order by pu.created_at desc nulls last, pu.user_id desc
      ),
      '[]'::jsonb
    )
  into v_users
  from paged_users pu
  left join order_stats os on os.user_id = pu.user_id;

  return jsonb_build_object(
    'users', coalesce(v_users, '[]'::jsonb),
    'page', v_safe_page,
    'pageSize', v_page_size,
    'totalCount', v_total_count,
    'totalPages', v_total_pages
  );
end;
$$;

grant execute on function public.admin_bot_dashboard_snapshot(integer) to authenticated;
grant execute on function public.admin_bot_users_snapshot_page(integer, integer, text) to authenticated;

-- ============================================================================
-- END: supabase_schema_bot_admin_analytics_perf.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_bot_admin_users_snapshot_v2.sql
-- ============================================================================

create extension if not exists pg_trgm with schema extensions;

create index if not exists users_username_trgm_idx
  on public.users
  using gin ((lower(coalesce(username, ''))) extensions.gin_trgm_ops);

create index if not exists users_display_name_trgm_idx
  on public.users
  using gin ((
    lower(
      coalesce(
        nullif(
          btrim(
            coalesce(first_name, '') || ' ' || coalesce(last_name, '')
          ),
          ''
        ),
        ''
      )
    )
  ) extensions.gin_trgm_ops);

create index if not exists users_user_id_text_trgm_idx
  on public.users
  using gin (((user_id)::text) extensions.gin_trgm_ops);

create or replace function public.admin_bot_users_snapshot_page_v2(
  p_page integer default 1,
  p_page_size integer default 50,
  p_search text default null,
  p_filter text default 'all',
  p_sort text default 'newest'
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_page integer := greatest(1, coalesce(p_page, 1));
  v_page_size integer := greatest(1, least(coalesce(p_page_size, 50), 200));
  v_search text := lower(coalesce(nullif(btrim(p_search), ''), ''));
  v_search_no_at text := regexp_replace(v_search, '^@+', '');
  v_filter text := lower(coalesce(nullif(btrim(p_filter), ''), 'all'));
  v_sort text := lower(coalesce(nullif(btrim(p_sort), ''), 'newest'));
  v_result jsonb;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  if v_filter not in ('all', 'with_revenue', 'without_revenue', 'with_orders') then
    v_filter := 'all';
  end if;

  if v_sort not in (
    'newest',
    'oldest',
    'username_asc',
    'username_desc',
    'revenue_desc',
    'revenue_asc',
    'order_count_desc',
    'order_count_asc'
  ) then
    v_sort := 'newest';
  end if;

  with order_stats as (
    select
      o.user_id,
      count(*)::bigint as order_count,
      coalesce(sum(coalesce(o.price, 0)), 0)::bigint as total_paid
    from public.orders o
    group by o.user_id
  ),
  base_users as (
    select
      u.user_id,
      u.username,
      nullif(
        btrim(
          coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')
        ),
        ''
      ) as display_name,
      lower(coalesce(u.username, '')) as username_search,
      lower(
        coalesce(
          nullif(
            btrim(
              coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')
            ),
            ''
          ),
          ''
        )
      ) as display_name_search,
      (u.user_id)::text as user_id_search,
      coalesce(u.balance, 0) as balance,
      coalesce(u.balance_usdt, 0) as balance_usdt,
      u.language,
      u.created_at,
      coalesce(os.order_count, 0)::bigint as order_count,
      coalesce(os.total_paid, 0)::bigint as total_paid
    from public.users u
    left join order_stats os on os.user_id = u.user_id
  ),
  filtered as materialized (
    select *
    from base_users bu
    where
      (
        v_search = ''
        or bu.user_id_search ilike '%' || v_search_no_at || '%'
        or bu.username_search like '%' || v_search || '%'
        or bu.username_search like '%' || v_search_no_at || '%'
        or bu.display_name_search like '%' || v_search || '%'
      )
      and (
        v_filter = 'all'
        or (v_filter = 'with_revenue' and bu.total_paid > 0)
        or (v_filter = 'without_revenue' and bu.total_paid <= 0)
        or (v_filter = 'with_orders' and bu.order_count > 0)
      )
  ),
  totals as (
    select
      count(*)::bigint as total_count,
      greatest(1, ceiling(count(*)::numeric / v_page_size)::integer) as total_pages
    from filtered
  ),
  meta as (
    select
      total_count,
      total_pages,
      least(v_page, total_pages) as safe_page
    from totals
  ),
  ranked as (
    select
      f.*,
      row_number() over (
        order by
          case when v_sort = 'newest' then f.created_at end desc nulls last,
          case when v_sort = 'oldest' then f.created_at end asc nulls last,
          case when v_sort = 'username_asc' then f.username_search end asc nulls last,
          case when v_sort = 'username_desc' then f.username_search end desc nulls last,
          case when v_sort = 'revenue_desc' then f.total_paid end desc nulls last,
          case when v_sort = 'revenue_asc' then f.total_paid end asc nulls last,
          case when v_sort = 'order_count_desc' then f.order_count end desc nulls last,
          case when v_sort = 'order_count_asc' then f.order_count end asc nulls last,
          f.created_at desc nulls last,
          f.user_id desc
      ) as row_number
    from filtered f
  ),
  paged as (
    select r.*
    from ranked r
    cross join meta m
    where
      r.row_number > ((m.safe_page - 1) * v_page_size)
      and r.row_number <= (m.safe_page * v_page_size)
  )
  select jsonb_build_object(
    'users',
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'user_id', p.user_id,
            'username', p.username,
            'display_name', p.display_name,
            'balance', p.balance,
            'balance_usdt', p.balance_usdt,
            'language', p.language,
            'created_at', p.created_at,
            'order_count', p.order_count,
            'total_paid', p.total_paid
          )
          order by p.row_number
        )
        from paged p
      ),
      '[]'::jsonb
    ),
    'page', coalesce((select safe_page from meta), 1),
    'pageSize', v_page_size,
    'totalCount', coalesce((select total_count from meta), 0),
    'totalPages', coalesce((select total_pages from meta), 1)
  )
  into v_result;

  return coalesce(
    v_result,
    jsonb_build_object(
      'users', '[]'::jsonb,
      'page', 1,
      'pageSize', v_page_size,
      'totalCount', 0,
      'totalPages', 1
    )
  );
end;
$$;

grant execute on function public.admin_bot_users_snapshot_page_v2(integer, integer, text, text, text) to authenticated;

-- ============================================================================
-- END: supabase_schema_bot_admin_users_snapshot_v2.sql
-- ============================================================================

-- ============================================================================
-- BEGIN: supabase_schema_bot_binance_onchain.sql
-- ============================================================================

-- Binance on-chain auto payment for Telegram Bot direct orders
-- Run after base schema / previous migrations.

-- Remove legacy manual Binance deposit flow.
drop function if exists public.admin_confirm_binance_deposit(bigint);
drop function if exists public.admin_cancel_binance_deposit(bigint);
drop table if exists public.binance_deposits cascade;

-- Direct-order payment-channel metadata.
alter table public.direct_orders add column if not exists payment_channel text default 'vietqr';
alter table public.direct_orders add column if not exists payment_asset text;
alter table public.direct_orders add column if not exists payment_network text;
alter table public.direct_orders add column if not exists payment_amount_asset numeric;
alter table public.direct_orders add column if not exists payment_rate_vnd numeric;
alter table public.direct_orders add column if not exists payment_address text;
alter table public.direct_orders add column if not exists payment_address_tag text;
alter table public.direct_orders add column if not exists external_payment_id text;
alter table public.direct_orders add column if not exists external_tx_id text;
alter table public.direct_orders add column if not exists external_paid_at timestamptz;

update public.direct_orders
set payment_channel = 'vietqr'
where payment_channel is null;

create index if not exists direct_orders_status_payment_channel_idx
  on public.direct_orders (status, payment_channel, created_at desc);

create index if not exists direct_orders_external_payment_idx
  on public.direct_orders (external_payment_id);

create index if not exists direct_orders_external_tx_idx
  on public.direct_orders (external_tx_id);

create unique index if not exists direct_orders_pending_binance_amount_idx
  on public.direct_orders (payment_channel, payment_asset, payment_network, payment_amount_asset)
  where status = 'pending'
    and payment_channel = 'binance_onchain'
    and payment_amount_asset is not null;

-- Binance idempotency table.
create table if not exists public.binance_processed_deposits (
  payment_id text primary key,
  tx_id text,
  direct_order_id bigint references public.direct_orders(id) on delete set null,
  amount_asset numeric,
  payment_asset text,
  payment_network text,
  processed_at timestamptz default now()
);

create index if not exists binance_processed_deposits_tx_id_idx
  on public.binance_processed_deposits (tx_id);

alter table public.binance_processed_deposits enable row level security;
drop policy if exists "Admins can access binance processed deposits" on public.binance_processed_deposits;
create policy "Admins can access binance processed deposits" on public.binance_processed_deposits
  for all using (public.is_admin()) with check (public.is_admin());

-- Rebuild reset_sequences so it no longer references the removed legacy table.
create or replace function public.reset_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(pg_get_serial_sequence('public.products', 'id'), coalesce((select max(id) from public.products), 1), true);
  perform setval(pg_get_serial_sequence('public.stock', 'id'), coalesce((select max(id) from public.stock), 1), true);
  perform setval(pg_get_serial_sequence('public.orders', 'id'), coalesce((select max(id) from public.orders), 1), true);
  perform setval(pg_get_serial_sequence('public.deposits', 'id'), coalesce((select max(id) from public.deposits), 1), true);
  perform setval(pg_get_serial_sequence('public.withdrawals', 'id'), coalesce((select max(id) from public.withdrawals), 1), true);
  perform setval(pg_get_serial_sequence('public.usdt_withdrawals', 'id'), coalesce((select max(id) from public.usdt_withdrawals), 1), true);
  perform setval(pg_get_serial_sequence('public.direct_orders', 'id'), coalesce((select max(id) from public.direct_orders), 1), true);
  perform setval(pg_get_serial_sequence('public.format_templates', 'id'), coalesce((select max(id) from public.format_templates), 1), true);
end $$;

-- Atomic helper for Telegram Bot Binance direct orders.
create or replace function public.create_binance_direct_order(
  p_user_id bigint,
  p_product_id bigint,
  p_quantity integer,
  p_bonus_quantity integer,
  p_unit_price bigint,
  p_amount bigint,
  p_code text,
  p_payment_asset text,
  p_payment_network text,
  p_payment_amount_asset numeric,
  p_payment_rate_vnd numeric,
  p_payment_address text,
  p_payment_address_tag text
)
returns table (
  direct_order_id bigint,
  code text,
  payment_asset text,
  payment_network text,
  payment_amount_asset numeric,
  payment_address text,
  payment_address_tag text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.direct_orders%rowtype;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  insert into public.direct_orders (
    user_id,
    product_id,
    quantity,
    bonus_quantity,
    unit_price,
    amount,
    code,
    payment_channel,
    payment_asset,
    payment_network,
    payment_amount_asset,
    payment_rate_vnd,
    payment_address,
    payment_address_tag,
    created_at
  )
  values (
    p_user_id,
    p_product_id,
    p_quantity,
    p_bonus_quantity,
    p_unit_price,
    p_amount,
    p_code,
    'binance_onchain',
    p_payment_asset,
    p_payment_network,
    p_payment_amount_asset,
    p_payment_rate_vnd,
    p_payment_address,
    nullif(p_payment_address_tag, ''),
    now()
  )
  returning * into v_order;

  return query
  select
    v_order.id,
    v_order.code,
    v_order.payment_asset,
    v_order.payment_network,
    v_order.payment_amount_asset,
    v_order.payment_address,
    v_order.payment_address_tag,
    v_order.created_at;
end $$;

grant execute on function public.create_binance_direct_order(
  bigint,
  bigint,
  integer,
  integer,
  bigint,
  bigint,
  text,
  text,
  text,
  numeric,
  numeric,
  text,
  text
) to authenticated;

-- ============================================================================
-- END: supabase_schema_bot_binance_onchain.sql
-- ============================================================================
