-- Telegram Bot product folders/categories.
-- New file on purpose: do not append this into older SQL files.

create table if not exists public.bot_product_folders (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_position integer,
  created_at timestamptz not null default now()
);

create unique index if not exists bot_product_folders_name_lower_idx
  on public.bot_product_folders (lower(btrim(name)));

create index if not exists idx_bot_product_folders_sort
  on public.bot_product_folders (sort_position, id);

alter table public.products
  add column if not exists bot_folder_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_bot_folder_id_fkey'
  ) then
    alter table public.products
      add constraint products_bot_folder_id_fkey
      foreign key (bot_folder_id)
      references public.bot_product_folders(id)
      on delete set null;
  end if;
end $$;

create index if not exists idx_products_bot_folder_sort
  on public.products (bot_folder_id, sort_position, id);

alter table public.bot_product_folders enable row level security;
drop policy if exists "Admins can access bot product folders" on public.bot_product_folders;
create policy "Admins can access bot product folders" on public.bot_product_folders
  for all using (public.is_admin()) with check (public.is_admin());

drop function if exists public.get_products_with_stock();
create or replace function public.get_products_with_stock()
returns table (
  id bigint,
  name text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  bot_folder_id bigint,
  stock bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.price,
    p.price_usdt,
    p.price_tiers,
    p.promo_buy_quantity,
    p.promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    p.website_promo_buy_quantity,
    p.website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    p.website_enabled,
    p.description,
    p.format_data,
    p.bot_folder_id,
    coalesce(s.stock, 0) as stock
  from public.products p
  left join (
    select product_id, count(*) as stock
    from public.stock
    where sold = false
    group by product_id
  ) s on s.product_id = p.id
  where (auth.role() = 'service_role' or public.is_admin())
    and coalesce(p.is_deleted, false) = false
    and coalesce(p.is_hidden, false) = false
  order by p.id;
$$;

drop function if exists public.get_product_with_stock(bigint);
create or replace function public.get_product_with_stock(p_id bigint)
returns table (
  id bigint,
  name text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  bot_folder_id bigint,
  stock bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.price,
    p.price_usdt,
    p.price_tiers,
    p.promo_buy_quantity,
    p.promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    p.website_promo_buy_quantity,
    p.website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    p.website_enabled,
    p.description,
    p.format_data,
    p.bot_folder_id,
    coalesce(s.stock, 0) as stock
  from public.products p
  left join (
    select product_id, count(*) as stock
    from public.stock
    where sold = false
    group by product_id
  ) s on s.product_id = p.id
  where (auth.role() = 'service_role' or public.is_admin())
    and p.id = p_id
    and coalesce(p.is_deleted, false) = false
    and coalesce(p.is_hidden, false) = false
  limit 1;
$$;
