-- License management for external extensions

CREATE OR REPLACE FUNCTION public.set_row_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.license_extensions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT license_extensions_code_format_chk CHECK (code ~ '^[A-Z0-9_-]+$')
);

CREATE TABLE IF NOT EXISTS public.license_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  extension_id BIGINT NOT NULL REFERENCES public.license_extensions(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  key_hash TEXT NOT NULL UNIQUE,
  key_prefix TEXT NOT NULL,
  key_suffix TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  expires_at TIMESTAMPTZ NOT NULL,
  note TEXT,
  device_limit_mode TEXT NOT NULL DEFAULT 'single_device',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT license_keys_status_chk CHECK (status IN ('active', 'expired', 'revoked')),
  CONSTRAINT license_keys_device_limit_mode_chk CHECK (device_limit_mode IN ('single_device', 'unlimited_devices'))
);

ALTER TABLE public.license_keys
  ADD COLUMN IF NOT EXISTS device_limit_mode TEXT;

UPDATE public.license_keys
SET device_limit_mode = 'single_device'
WHERE COALESCE(TRIM(device_limit_mode), '') = '';

ALTER TABLE public.license_keys
  ALTER COLUMN device_limit_mode SET DEFAULT 'single_device';

ALTER TABLE public.license_keys
  ALTER COLUMN device_limit_mode SET NOT NULL;

ALTER TABLE public.license_keys
  DROP CONSTRAINT IF EXISTS license_keys_device_limit_mode_chk;

ALTER TABLE public.license_keys
  ADD CONSTRAINT license_keys_device_limit_mode_chk
  CHECK (device_limit_mode IN ('single_device', 'unlimited_devices'));

CREATE TABLE IF NOT EXISTS public.license_activations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_key_id BIGINT NOT NULL REFERENCES public.license_keys(id) ON UPDATE CASCADE ON DELETE CASCADE,
  fingerprint TEXT NOT NULL,
  activation_token_hash TEXT NOT NULL UNIQUE,
  activated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deactivated_at TIMESTAMPTZ,
  deactivation_reason TEXT,
  last_ip TEXT,
  last_user_agent TEXT,
  last_version TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.license_check_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_key_id BIGINT REFERENCES public.license_keys(id) ON UPDATE CASCADE ON DELETE SET NULL,
  extension_code TEXT NOT NULL,
  fingerprint TEXT,
  request_type TEXT NOT NULL,
  result_status TEXT NOT NULL,
  ip TEXT,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT license_check_logs_request_type_chk CHECK (request_type IN ('activate', 'validate')),
  CONSTRAINT license_check_logs_result_status_chk CHECK (
    result_status IN ('active', 'expired', 'revoked', 'extension_disabled', 'fingerprint_mismatch', 'not_found')
  )
);

CREATE INDEX IF NOT EXISTS idx_license_extensions_code
  ON public.license_extensions (code);

CREATE INDEX IF NOT EXISTS idx_license_keys_extension_created
  ON public.license_keys (extension_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_license_keys_status_expires
  ON public.license_keys (status, expires_at DESC);

DROP INDEX IF EXISTS public.idx_license_activations_active_key;

CREATE UNIQUE INDEX IF NOT EXISTS idx_license_activations_active_key_fingerprint
  ON public.license_activations (license_key_id, fingerprint)
  WHERE deactivated_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_license_activations_last_checked
  ON public.license_activations (last_checked_at DESC);

CREATE INDEX IF NOT EXISTS idx_license_activations_fingerprint
  ON public.license_activations (fingerprint);

CREATE INDEX IF NOT EXISTS idx_license_check_logs_created_at
  ON public.license_check_logs (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_license_check_logs_extension_code
  ON public.license_check_logs (extension_code, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_license_check_logs_license_key_id
  ON public.license_check_logs (license_key_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.prevent_license_extension_code_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.code IS DISTINCT FROM NEW.code THEN
    RAISE EXCEPTION 'extension_code_immutable';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_license_extensions_code_immutable ON public.license_extensions;
CREATE TRIGGER trg_license_extensions_code_immutable
BEFORE UPDATE ON public.license_extensions
FOR EACH ROW
EXECUTE FUNCTION public.prevent_license_extension_code_change();

DROP TRIGGER IF EXISTS trg_license_extensions_updated_at ON public.license_extensions;
CREATE TRIGGER trg_license_extensions_updated_at
BEFORE UPDATE ON public.license_extensions
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

DROP TRIGGER IF EXISTS trg_license_keys_updated_at ON public.license_keys;
CREATE TRIGGER trg_license_keys_updated_at
BEFORE UPDATE ON public.license_keys
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

DROP TRIGGER IF EXISTS trg_license_activations_updated_at ON public.license_activations;
CREATE TRIGGER trg_license_activations_updated_at
BEFORE UPDATE ON public.license_activations
FOR EACH ROW
EXECUTE FUNCTION public.set_row_updated_at();

CREATE OR REPLACE FUNCTION public.license_key_effective_status(
  p_status TEXT,
  p_expires_at TIMESTAMPTZ
)
RETURNS TEXT
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
  IF COALESCE(p_status, '') = 'revoked' THEN
    RETURN 'revoked';
  END IF;

  IF COALESCE(p_status, '') = 'expired' OR (p_expires_at IS NOT NULL AND p_expires_at <= NOW()) THEN
    RETURN 'expired';
  END IF;

  RETURN 'active';
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_license_key_expired(
  p_license_key_id BIGINT
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE public.license_keys
  SET status = 'expired'
  WHERE id = p_license_key_id
    AND status = 'active'
    AND expires_at <= NOW();
END;
$$;

CREATE OR REPLACE FUNCTION public.log_license_check(
  p_license_key_id BIGINT,
  p_extension_code TEXT,
  p_fingerprint TEXT,
  p_request_type TEXT,
  p_result_status TEXT,
  p_ip TEXT DEFAULT NULL,
  p_user_agent TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.license_check_logs (
    license_key_id,
    extension_code,
    fingerprint,
    request_type,
    result_status,
    ip,
    user_agent
  )
  VALUES (
    p_license_key_id,
    COALESCE(NULLIF(TRIM(p_extension_code), ''), 'UNKNOWN'),
    NULLIF(TRIM(COALESCE(p_fingerprint, '')), ''),
    p_request_type,
    p_result_status,
    NULLIF(TRIM(COALESCE(p_ip, '')), ''),
    NULLIF(LEFT(TRIM(COALESCE(p_user_agent, '')), 512), '')
  );
END;
$$;

DROP FUNCTION IF EXISTS public.activate_license_key(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT);
CREATE OR REPLACE FUNCTION public.activate_license_key(
  p_extension_code TEXT,
  p_key_hash TEXT,
  p_activation_token_hash TEXT,
  p_fingerprint TEXT,
  p_ip TEXT DEFAULT NULL,
  p_user_agent TEXT DEFAULT NULL,
  p_version TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_extension public.license_extensions%ROWTYPE;
  v_license_key public.license_keys%ROWTYPE;
  v_existing_activation public.license_activations%ROWTYPE;
  v_other_activation public.license_activations%ROWTYPE;
  v_extension_code TEXT := UPPER(TRIM(COALESCE(p_extension_code, '')));
  v_key_hash TEXT := TRIM(COALESCE(p_key_hash, ''));
  v_token_hash TEXT := TRIM(COALESCE(p_activation_token_hash, ''));
  v_fingerprint TEXT := TRIM(COALESCE(p_fingerprint, ''));
  v_effective_status TEXT;
  v_device_limit_mode TEXT;
BEGIN
  IF v_extension_code = '' OR v_key_hash = '' OR v_token_hash = '' OR v_fingerprint = '' THEN
    PERFORM public.log_license_check(NULL, v_extension_code, v_fingerprint, 'activate', 'not_found', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'not_found', 'expires_at', NULL);
  END IF;

  SELECT *
  INTO v_extension
  FROM public.license_extensions
  WHERE code = v_extension_code
  LIMIT 1;

  IF NOT FOUND THEN
    PERFORM public.log_license_check(NULL, v_extension_code, v_fingerprint, 'activate', 'not_found', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'not_found', 'expires_at', NULL);
  END IF;

  IF NOT v_extension.is_active THEN
    PERFORM public.log_license_check(NULL, v_extension_code, v_fingerprint, 'activate', 'extension_disabled', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'extension_disabled', 'expires_at', NULL);
  END IF;

  SELECT *
  INTO v_license_key
  FROM public.license_keys
  WHERE extension_id = v_extension.id
    AND key_hash = v_key_hash
  LIMIT 1
  FOR UPDATE;

  IF NOT FOUND THEN
    PERFORM public.log_license_check(NULL, v_extension_code, v_fingerprint, 'activate', 'not_found', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'not_found', 'expires_at', NULL);
  END IF;

  v_effective_status := public.license_key_effective_status(v_license_key.status, v_license_key.expires_at);
  IF v_effective_status = 'expired' THEN
    PERFORM public.mark_license_key_expired(v_license_key.id);
    PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'activate', 'expired', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'expired', 'expires_at', v_license_key.expires_at);
  END IF;

  IF v_effective_status = 'revoked' THEN
    PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'activate', 'revoked', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'revoked', 'expires_at', v_license_key.expires_at);
  END IF;

  v_device_limit_mode := COALESCE(NULLIF(TRIM(COALESCE(v_license_key.device_limit_mode, '')), ''), 'single_device');

  SELECT *
  INTO v_existing_activation
  FROM public.license_activations
  WHERE license_key_id = v_license_key.id
    AND fingerprint = v_fingerprint
    AND deactivated_at IS NULL
  ORDER BY activated_at DESC
  LIMIT 1
  FOR UPDATE;

  IF FOUND THEN
    UPDATE public.license_activations
    SET activation_token_hash = v_token_hash,
        last_checked_at = NOW(),
        last_ip = NULLIF(TRIM(COALESCE(p_ip, '')), ''),
        last_user_agent = NULLIF(LEFT(TRIM(COALESCE(p_user_agent, '')), 512), ''),
        last_version = NULLIF(LEFT(TRIM(COALESCE(p_version, '')), 120), '')
    WHERE id = v_existing_activation.id;

    PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'activate', 'active', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', TRUE, 'status', 'active', 'expires_at', v_license_key.expires_at);
  END IF;

  IF v_device_limit_mode <> 'unlimited_devices' THEN
    SELECT *
    INTO v_other_activation
    FROM public.license_activations
    WHERE license_key_id = v_license_key.id
      AND deactivated_at IS NULL
    ORDER BY activated_at DESC
    LIMIT 1
    FOR UPDATE;

    IF FOUND THEN
      PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'activate', 'fingerprint_mismatch', p_ip, p_user_agent);
      RETURN jsonb_build_object('valid', FALSE, 'status', 'fingerprint_mismatch', 'expires_at', v_license_key.expires_at);
    END IF;
  END IF;

  BEGIN
    INSERT INTO public.license_activations (
      license_key_id,
      fingerprint,
      activation_token_hash,
      last_ip,
      last_user_agent,
      last_version
    )
    VALUES (
      v_license_key.id,
      v_fingerprint,
      v_token_hash,
      NULLIF(TRIM(COALESCE(p_ip, '')), ''),
      NULLIF(LEFT(TRIM(COALESCE(p_user_agent, '')), 512), ''),
      NULLIF(LEFT(TRIM(COALESCE(p_version, '')), 120), '')
    )
    RETURNING *
    INTO v_existing_activation;
  EXCEPTION
    WHEN unique_violation THEN
      SELECT *
      INTO v_existing_activation
      FROM public.license_activations
      WHERE license_key_id = v_license_key.id
        AND fingerprint = v_fingerprint
        AND deactivated_at IS NULL
      ORDER BY activated_at DESC
      LIMIT 1
      FOR UPDATE;

      IF NOT FOUND THEN
        RAISE;
      END IF;

      UPDATE public.license_activations
      SET activation_token_hash = v_token_hash,
          last_checked_at = NOW(),
          last_ip = NULLIF(TRIM(COALESCE(p_ip, '')), ''),
          last_user_agent = NULLIF(LEFT(TRIM(COALESCE(p_user_agent, '')), 512), ''),
          last_version = NULLIF(LEFT(TRIM(COALESCE(p_version, '')), 120), '')
      WHERE id = v_existing_activation.id;
  END;

  PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'activate', 'active', p_ip, p_user_agent);
  RETURN jsonb_build_object('valid', TRUE, 'status', 'active', 'expires_at', v_license_key.expires_at);
END;
$$;

DROP FUNCTION IF EXISTS public.validate_license_activation(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT);
CREATE OR REPLACE FUNCTION public.validate_license_activation(
  p_extension_code TEXT,
  p_activation_token_hash TEXT,
  p_fingerprint TEXT,
  p_ip TEXT DEFAULT NULL,
  p_user_agent TEXT DEFAULT NULL,
  p_version TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_extension public.license_extensions%ROWTYPE;
  v_license_key public.license_keys%ROWTYPE;
  v_activation public.license_activations%ROWTYPE;
  v_extension_code TEXT := UPPER(TRIM(COALESCE(p_extension_code, '')));
  v_token_hash TEXT := TRIM(COALESCE(p_activation_token_hash, ''));
  v_fingerprint TEXT := TRIM(COALESCE(p_fingerprint, ''));
  v_effective_status TEXT;
BEGIN
  IF v_extension_code = '' OR v_token_hash = '' OR v_fingerprint = '' THEN
    PERFORM public.log_license_check(NULL, v_extension_code, v_fingerprint, 'validate', 'not_found', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'not_found', 'expires_at', NULL);
  END IF;

  SELECT *
  INTO v_activation
  FROM public.license_activations
  WHERE activation_token_hash = v_token_hash
  LIMIT 1;

  IF NOT FOUND THEN
    PERFORM public.log_license_check(NULL, v_extension_code, v_fingerprint, 'validate', 'not_found', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'not_found', 'expires_at', NULL);
  END IF;

  IF v_activation.deactivated_at IS NOT NULL THEN
    PERFORM public.log_license_check(NULL, v_extension_code, v_fingerprint, 'validate', 'not_found', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'not_found', 'expires_at', NULL);
  END IF;

  SELECT *
  INTO v_license_key
  FROM public.license_keys
  WHERE id = v_activation.license_key_id
  LIMIT 1;

  IF NOT FOUND THEN
    PERFORM public.log_license_check(NULL, v_extension_code, v_fingerprint, 'validate', 'not_found', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'not_found', 'expires_at', NULL);
  END IF;

  SELECT *
  INTO v_extension
  FROM public.license_extensions
  WHERE id = v_license_key.extension_id
  LIMIT 1;

  IF NOT FOUND OR v_extension.code IS DISTINCT FROM v_extension_code THEN
    PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'validate', 'not_found', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'not_found', 'expires_at', NULL);
  END IF;

  IF NOT v_extension.is_active THEN
    PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'validate', 'extension_disabled', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'extension_disabled', 'expires_at', v_license_key.expires_at);
  END IF;

  v_effective_status := public.license_key_effective_status(v_license_key.status, v_license_key.expires_at);
  IF v_effective_status = 'expired' THEN
    PERFORM public.mark_license_key_expired(v_license_key.id);
    PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'validate', 'expired', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'expired', 'expires_at', v_license_key.expires_at);
  END IF;

  IF v_effective_status = 'revoked' THEN
    PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'validate', 'revoked', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'revoked', 'expires_at', v_license_key.expires_at);
  END IF;

  IF v_activation.fingerprint IS DISTINCT FROM v_fingerprint THEN
    PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'validate', 'fingerprint_mismatch', p_ip, p_user_agent);
    RETURN jsonb_build_object('valid', FALSE, 'status', 'fingerprint_mismatch', 'expires_at', v_license_key.expires_at);
  END IF;

  UPDATE public.license_activations
  SET last_checked_at = NOW(),
      last_ip = NULLIF(TRIM(COALESCE(p_ip, '')), ''),
      last_user_agent = NULLIF(LEFT(TRIM(COALESCE(p_user_agent, '')), 512), ''),
      last_version = NULLIF(LEFT(TRIM(COALESCE(p_version, '')), 120), '')
  WHERE id = v_activation.id;

  PERFORM public.log_license_check(v_license_key.id, v_extension_code, v_fingerprint, 'validate', 'active', p_ip, p_user_agent);
  RETURN jsonb_build_object('valid', TRUE, 'status', 'active', 'expires_at', v_license_key.expires_at);
END;
$$;

REVOKE ALL ON FUNCTION public.activate_license_key(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.activate_license_key(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO service_role;

REVOKE ALL ON FUNCTION public.validate_license_activation(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.validate_license_activation(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO service_role;

REVOKE ALL ON FUNCTION public.log_license_check(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.log_license_check(BIGINT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO service_role;

ALTER TABLE public.license_extensions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can access license extensions" ON public.license_extensions;
CREATE POLICY "Admins can access license extensions" ON public.license_extensions
FOR ALL
USING (public.is_admin())
WITH CHECK (public.is_admin());

ALTER TABLE public.license_keys ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can access license keys" ON public.license_keys;
CREATE POLICY "Admins can access license keys" ON public.license_keys
FOR ALL
USING (public.is_admin())
WITH CHECK (public.is_admin());

ALTER TABLE public.license_activations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can access license activations" ON public.license_activations;
CREATE POLICY "Admins can access license activations" ON public.license_activations
FOR ALL
USING (public.is_admin())
WITH CHECK (public.is_admin());

ALTER TABLE public.license_check_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can access license logs" ON public.license_check_logs;
CREATE POLICY "Admins can access license logs" ON public.license_check_logs
FOR ALL
USING (public.is_admin())
WITH CHECK (public.is_admin());
