-- Durable Telegram broadcast job queue for admin dashboard bulk sends.

create table if not exists public.telegram_broadcast_jobs (
  id bigint generated by default as identity primary key,
  status text not null default 'queued',
  message text not null,
  total_candidates integer not null default 0,
  total_targets integer not null default 0,
  skipped_count integer not null default 0,
  blacklisted_count integer not null default 0,
  last_error text null,
  started_at timestamptz null,
  finished_at timestamptz null,
  last_heartbeat_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint telegram_broadcast_jobs_status_check check (status in ('queued', 'running', 'completed', 'failed', 'cancelled'))
);

create table if not exists public.telegram_broadcast_job_targets (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.telegram_broadcast_jobs(id) on delete cascade,
  chat_id bigint not null,
  status text not null default 'pending',
  attempt_count integer not null default 0,
  error_text text null,
  message_id bigint null,
  sent_at timestamptz null,
  last_attempt_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint telegram_broadcast_job_targets_unique unique (job_id, chat_id),
  constraint telegram_broadcast_job_targets_status_check check (status in ('pending', 'sending', 'sent', 'failed'))
);

create index if not exists idx_telegram_broadcast_jobs_status
  on public.telegram_broadcast_jobs (status, created_at desc, id desc);

create index if not exists idx_telegram_broadcast_job_targets_job_status
  on public.telegram_broadcast_job_targets (job_id, status, id);

create or replace function public.set_telegram_broadcast_jobs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.set_telegram_broadcast_job_targets_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_telegram_broadcast_jobs_updated_at on public.telegram_broadcast_jobs;
create trigger trg_telegram_broadcast_jobs_updated_at
before update on public.telegram_broadcast_jobs
for each row
execute function public.set_telegram_broadcast_jobs_updated_at();

drop trigger if exists trg_telegram_broadcast_job_targets_updated_at on public.telegram_broadcast_job_targets;
create trigger trg_telegram_broadcast_job_targets_updated_at
before update on public.telegram_broadcast_job_targets
for each row
execute function public.set_telegram_broadcast_job_targets_updated_at();

alter table public.telegram_broadcast_jobs enable row level security;
alter table public.telegram_broadcast_job_targets enable row level security;

drop policy if exists "Admins can read telegram broadcast jobs" on public.telegram_broadcast_jobs;
create policy "Admins can read telegram broadcast jobs"
on public.telegram_broadcast_jobs
for select
using (public.is_admin());

drop policy if exists "Admins can insert telegram broadcast jobs" on public.telegram_broadcast_jobs;
create policy "Admins can insert telegram broadcast jobs"
on public.telegram_broadcast_jobs
for insert
with check (public.is_admin());

drop policy if exists "Admins can update telegram broadcast jobs" on public.telegram_broadcast_jobs;
create policy "Admins can update telegram broadcast jobs"
on public.telegram_broadcast_jobs
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete telegram broadcast jobs" on public.telegram_broadcast_jobs;
create policy "Admins can delete telegram broadcast jobs"
on public.telegram_broadcast_jobs
for delete
using (public.is_admin());

drop policy if exists "Admins can read telegram broadcast job targets" on public.telegram_broadcast_job_targets;
create policy "Admins can read telegram broadcast job targets"
on public.telegram_broadcast_job_targets
for select
using (public.is_admin());

drop policy if exists "Admins can insert telegram broadcast job targets" on public.telegram_broadcast_job_targets;
create policy "Admins can insert telegram broadcast job targets"
on public.telegram_broadcast_job_targets
for insert
with check (public.is_admin());

drop policy if exists "Admins can update telegram broadcast job targets" on public.telegram_broadcast_job_targets;
create policy "Admins can update telegram broadcast job targets"
on public.telegram_broadcast_job_targets
for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete telegram broadcast job targets" on public.telegram_broadcast_job_targets;
create policy "Admins can delete telegram broadcast job targets"
on public.telegram_broadcast_job_targets
for delete
using (public.is_admin());
