-- Canonical Telegram Bot product stock RPCs.
-- Apply this file LAST after product position, soft-delete, website channel split,
-- and bot product folder migrations. It intentionally rebuilds RPC return shapes.

-- Keep optional columns present so this canonical RPC can be applied on databases
-- that were upgraded through different split-migration paths.
alter table public.products
  add column if not exists price_usdt numeric default 0;

alter table public.products
  add column if not exists price_tiers jsonb;

alter table public.products
  add column if not exists promo_buy_quantity integer default 0;

alter table public.products
  add column if not exists promo_bonus_quantity integer default 0;

alter table public.products
  add column if not exists format_data text;

alter table public.products
  add column if not exists telegram_icon text;

comment on column public.products.telegram_icon is
  'Optional plain emoji/text fallback shown before the product name in Telegram Bot inline buttons when no custom emoji ID is set.';

alter table public.products
  add column if not exists telegram_icon_custom_emoji_id text;

comment on column public.products.telegram_icon_custom_emoji_id is
  'Optional Telegram custom emoji ID used as InlineKeyboardButton.icon_custom_emoji_id.';

alter table public.products
  add column if not exists sort_position integer;

alter table public.products
  add column if not exists is_hidden boolean not null default false;

alter table public.products
  add column if not exists is_deleted boolean not null default false;

alter table public.products
  add column if not exists deleted_at timestamptz;

alter table public.products
  add column if not exists bot_folder_id bigint;

alter table public.products
  add column if not exists website_name text;

alter table public.products
  add column if not exists website_price bigint;

alter table public.products
  add column if not exists website_price_tiers jsonb;

alter table public.products
  add column if not exists website_promo_buy_quantity integer default 0;

alter table public.products
  add column if not exists website_promo_bonus_quantity integer default 0;

alter table public.products
  add column if not exists website_banner_url text;

alter table public.products
  add column if not exists website_logo_url text;

alter table public.products
  add column if not exists website_enabled boolean default true;

create table if not exists public.bot_product_folders (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_position integer,
  created_at timestamptz not null default now()
);

create unique index if not exists bot_product_folders_name_lower_idx
  on public.bot_product_folders (lower(btrim(name)));

create index if not exists idx_bot_product_folders_sort
  on public.bot_product_folders (sort_position, id);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'products_bot_folder_id_fkey'
  ) then
    alter table public.products
      add constraint products_bot_folder_id_fkey
      foreign key (bot_folder_id)
      references public.bot_product_folders(id)
      on delete set null;
  end if;
end $$;

create index if not exists idx_products_visibility
  on public.products (is_deleted, is_hidden, id);

create index if not exists idx_products_sort_position
  on public.products (sort_position, id);

create index if not exists idx_products_bot_folder_sort
  on public.products (bot_folder_id, sort_position, id);

alter table public.bot_product_folders enable row level security;
drop policy if exists "Admins can access bot product folders" on public.bot_product_folders;
create policy "Admins can access bot product folders" on public.bot_product_folders
  for all using (public.is_admin()) with check (public.is_admin());

update public.products
set
  is_hidden = coalesce(is_hidden, false),
  is_deleted = coalesce(is_deleted, false),
  promo_buy_quantity = coalesce(promo_buy_quantity, 0),
  promo_bonus_quantity = coalesce(promo_bonus_quantity, 0),
  website_promo_buy_quantity = coalesce(website_promo_buy_quantity, 0),
  website_promo_bonus_quantity = coalesce(website_promo_bonus_quantity, 0),
  website_enabled = coalesce(website_enabled, true)
where
  is_hidden is null
  or is_deleted is null
  or promo_buy_quantity is null
  or promo_bonus_quantity is null
  or website_promo_buy_quantity is null
  or website_promo_bonus_quantity is null
  or website_enabled is null;

drop function if exists public.get_products_with_stock();
create or replace function public.get_products_with_stock()
returns table (
  id bigint,
  name text,
  telegram_icon text,
  telegram_icon_custom_emoji_id text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  sort_position integer,
  bot_folder_id bigint,
  stock bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.telegram_icon,
    p.telegram_icon_custom_emoji_id,
    p.price,
    p.price_usdt,
    p.price_tiers,
    coalesce(p.promo_buy_quantity, 0) as promo_buy_quantity,
    coalesce(p.promo_bonus_quantity, 0) as promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    coalesce(p.website_promo_buy_quantity, 0) as website_promo_buy_quantity,
    coalesce(p.website_promo_bonus_quantity, 0) as website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    coalesce(p.website_enabled, true) as website_enabled,
    p.description,
    p.format_data,
    p.sort_position,
    p.bot_folder_id,
    coalesce(s.stock, 0) as stock
  from public.products p
  left join (
    select product_id, count(*) as stock
    from public.stock
    where sold = false
    group by product_id
  ) s on s.product_id = p.id
  where (auth.role() = 'service_role' or public.is_admin())
    and coalesce(p.is_deleted, false) = false
    and coalesce(p.is_hidden, false) = false
  order by
    case when p.sort_position is null then 1 else 0 end,
    p.sort_position nulls last,
    p.id;
$$;

drop function if exists public.get_product_with_stock(bigint);
create or replace function public.get_product_with_stock(p_id bigint)
returns table (
  id bigint,
  name text,
  telegram_icon text,
  telegram_icon_custom_emoji_id text,
  price bigint,
  price_usdt numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  website_name text,
  website_price bigint,
  website_price_tiers jsonb,
  website_promo_buy_quantity integer,
  website_promo_bonus_quantity integer,
  website_banner_url text,
  website_logo_url text,
  website_enabled boolean,
  description text,
  format_data text,
  sort_position integer,
  bot_folder_id bigint,
  stock bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.name,
    p.telegram_icon,
    p.telegram_icon_custom_emoji_id,
    p.price,
    p.price_usdt,
    p.price_tiers,
    coalesce(p.promo_buy_quantity, 0) as promo_buy_quantity,
    coalesce(p.promo_bonus_quantity, 0) as promo_bonus_quantity,
    p.website_name,
    p.website_price,
    p.website_price_tiers,
    coalesce(p.website_promo_buy_quantity, 0) as website_promo_buy_quantity,
    coalesce(p.website_promo_bonus_quantity, 0) as website_promo_bonus_quantity,
    p.website_banner_url,
    p.website_logo_url,
    coalesce(p.website_enabled, true) as website_enabled,
    p.description,
    p.format_data,
    p.sort_position,
    p.bot_folder_id,
    coalesce(s.stock, 0) as stock
  from public.products p
  left join (
    select product_id, count(*) as stock
    from public.stock
    where sold = false
    group by product_id
  ) s on s.product_id = p.id
  where (auth.role() = 'service_role' or public.is_admin())
    and p.id = p_id
    and coalesce(p.is_deleted, false) = false
    and coalesce(p.is_hidden, false) = false
  limit 1;
$$;

revoke all on function public.get_products_with_stock() from PUBLIC, anon;
grant execute on function public.get_products_with_stock() to authenticated, service_role;

revoke all on function public.get_product_with_stock(bigint) from PUBLIC, anon;
grant execute on function public.get_product_with_stock(bigint) to authenticated, service_role;
