-- Telegram Bot Sale campaigns.
-- Apply after base product/order/direct-order/stock schema.

create table if not exists public.sale_campaigns (
  id bigint generated by default as identity primary key,
  name text not null,
  status text not null default 'draft'
    check (status in ('draft', 'scheduled', 'active', 'paused', 'ended', 'cancelled')),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  timezone text not null default 'Asia/Ho_Chi_Minh',
  default_telegram_icon text default 'SALE',
  default_telegram_icon_custom_emoji_id text default '6055192572056309981',
  total_quantity_limit integer,
  per_user_limit integer,
  notify_on_start boolean not null default false,
  notify_ending_soon boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at),
  check (total_quantity_limit is null or total_quantity_limit > 0),
  check (per_user_limit is null or per_user_limit > 0)
);

create index if not exists sale_campaigns_status_time_idx
  on public.sale_campaigns (status, starts_at, ends_at);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references public.sale_campaigns(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  sale_name text,
  sale_description text,
  sale_price_vnd bigint not null,
  sale_price_usdt numeric,
  original_price_vnd bigint,
  original_price_usdt numeric,
  discount_percent numeric,
  promo_buy_quantity integer not null default 0,
  promo_bonus_quantity integer not null default 0,
  stock_mode text not null default 'reserved_existing'
    check (stock_mode in ('reserved_existing', 'new_stock', 'mixed')),
  quantity_limit integer,
  per_user_limit integer,
  telegram_icon text default 'SALE',
  telegram_icon_custom_emoji_id text default '6055192572056309981',
  is_enabled boolean not null default true,
  sort_position integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (sale_price_vnd >= 0),
  check (sale_price_usdt is null or sale_price_usdt >= 0),
  check (promo_buy_quantity >= 0),
  check (promo_bonus_quantity >= 0),
  check (quantity_limit is null or quantity_limit > 0),
  check (per_user_limit is null or per_user_limit > 0)
);

create unique index if not exists sale_items_campaign_product_idx
  on public.sale_items (campaign_id, product_id);

create index if not exists sale_items_campaign_sort_idx
  on public.sale_items (campaign_id, sort_position, id);

create index if not exists sale_items_product_idx
  on public.sale_items (product_id);

create table if not exists public.sale_stock_reservations (
  id bigint generated by default as identity primary key,
  sale_item_id bigint not null references public.sale_items(id) on delete cascade,
  stock_id bigint not null references public.stock(id) on delete cascade,
  status text not null default 'available'
    check (status in ('available', 'held', 'sold', 'released')),
  held_direct_order_id bigint references public.direct_orders(id) on delete set null,
  held_until timestamptz,
  sold_order_id bigint references public.orders(id) on delete set null,
  sold_at timestamptz,
  released_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists sale_stock_reservations_live_stock_idx
  on public.sale_stock_reservations (stock_id)
  where released_at is null and status in ('available', 'held', 'sold');

create index if not exists sale_stock_reservations_item_status_idx
  on public.sale_stock_reservations (sale_item_id, status, held_until, id);

alter table public.orders add column if not exists sale_campaign_id bigint references public.sale_campaigns(id) on delete set null;
alter table public.orders add column if not exists sale_item_id bigint references public.sale_items(id) on delete set null;
alter table public.orders add column if not exists sale_original_unit_price bigint;
alter table public.orders add column if not exists sale_unit_price bigint;
alter table public.orders add column if not exists sale_discount_amount bigint;
alter table public.orders add column if not exists sale_paid_quantity integer;
alter table public.orders add column if not exists sale_bonus_quantity integer;
alter table public.orders add column if not exists sale_snapshot jsonb;

alter table public.direct_orders add column if not exists sale_campaign_id bigint references public.sale_campaigns(id) on delete set null;
alter table public.direct_orders add column if not exists sale_item_id bigint references public.sale_items(id) on delete set null;
alter table public.direct_orders add column if not exists sale_original_unit_price bigint;
alter table public.direct_orders add column if not exists sale_unit_price bigint;
alter table public.direct_orders add column if not exists sale_discount_amount bigint;
alter table public.direct_orders add column if not exists sale_paid_quantity integer;
alter table public.direct_orders add column if not exists sale_bonus_quantity integer;
alter table public.direct_orders add column if not exists sale_snapshot jsonb;
alter table public.direct_orders add column if not exists sale_hold_until timestamptz;

create index if not exists orders_sale_item_idx
  on public.orders (sale_item_id, user_id, created_at desc);

create index if not exists direct_orders_sale_item_status_idx
  on public.direct_orders (sale_item_id, status, created_at desc);

alter table public.sale_campaigns enable row level security;
drop policy if exists "Admins can access sale campaigns" on public.sale_campaigns;
create policy "Admins can access sale campaigns" on public.sale_campaigns
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.sale_items enable row level security;
drop policy if exists "Admins can access sale items" on public.sale_items;
create policy "Admins can access sale items" on public.sale_items
  for all using (public.is_admin()) with check (public.is_admin());

alter table public.sale_stock_reservations enable row level security;
drop policy if exists "Admins can access sale stock reservations" on public.sale_stock_reservations;
create policy "Admins can access sale stock reservations" on public.sale_stock_reservations
  for all using (public.is_admin()) with check (public.is_admin());

create or replace function public.set_sale_row_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_sale_campaigns_updated_at on public.sale_campaigns;
create trigger trg_sale_campaigns_updated_at
before update on public.sale_campaigns
for each row
execute function public.set_sale_row_updated_at();

drop trigger if exists trg_sale_items_updated_at on public.sale_items;
create trigger trg_sale_items_updated_at
before update on public.sale_items
for each row
execute function public.set_sale_row_updated_at();

create or replace function public.release_expired_sale_stock_holds(
  p_sale_item_id bigint default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer := 0;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  update public.direct_orders d
  set status = 'cancelled'
  where d.status = 'pending'
    and d.sale_item_id is not null
    and d.sale_hold_until is not null
    and d.sale_hold_until <= now()
    and (p_sale_item_id is null or d.sale_item_id = p_sale_item_id);

  update public.sale_stock_reservations r
  set status = 'available',
      held_direct_order_id = null,
      held_until = null
  where r.status = 'held'
    and r.held_until is not null
    and r.held_until <= now()
    and (p_sale_item_id is null or r.sale_item_id = p_sale_item_id);

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.get_active_sale_products()
returns table (
  sale_item_id bigint,
  sale_campaign_id bigint,
  product_id bigint,
  name text,
  telegram_icon text,
  telegram_icon_custom_emoji_id text,
  price bigint,
  price_usdt numeric,
  original_price bigint,
  original_price_usdt numeric,
  discount_percent numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  description text,
  format_data text,
  sort_position integer,
  stock bigint,
  campaign_name text,
  starts_at timestamptz,
  ends_at timestamptz,
  per_user_limit integer,
  quantity_limit integer,
  sold_quantity bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with active_items as (
    select
      si.*,
      c.name as campaign_name,
      c.starts_at,
      c.ends_at,
      c.total_quantity_limit as campaign_quantity_limit,
      c.per_user_limit as campaign_per_user_limit
    from public.sale_items si
    join public.sale_campaigns c on c.id = si.campaign_id
    where si.is_enabled = true
      and c.status in ('active', 'scheduled')
      and c.starts_at <= now()
      and c.ends_at > now()
  ),
  reservation_counts as (
    select
      r.sale_item_id,
      count(*) filter (
        where r.released_at is null
          and r.status in ('available', 'held')
          and (r.status = 'available' or coalesce(r.held_until, now() - interval '1 second') <= now())
          and coalesce(s.sold, false) = false
      )::bigint as available_stock,
      count(*) filter (where r.status = 'sold')::bigint as sold_stock
    from public.sale_stock_reservations r
    join public.stock s on s.id = r.stock_id
    group by r.sale_item_id
  ),
  campaign_sold as (
    select
      si.campaign_id,
      count(*) filter (where r.status = 'sold')::bigint as sold_stock
    from public.sale_items si
    left join public.sale_stock_reservations r on r.sale_item_id = si.id
    group by si.campaign_id
  )
  select
    ai.id as sale_item_id,
    ai.campaign_id as sale_campaign_id,
    p.id as product_id,
    coalesce(nullif(btrim(ai.sale_name), ''), p.name) as name,
    coalesce(nullif(btrim(ai.telegram_icon), ''), nullif(btrim(p.telegram_icon), ''), 'SALE') as telegram_icon,
    coalesce(
      nullif(btrim(ai.telegram_icon_custom_emoji_id), ''),
      nullif(btrim(c.default_telegram_icon_custom_emoji_id), ''),
      nullif(btrim(p.telegram_icon_custom_emoji_id), ''),
      '6055192572056309981'
    ) as telegram_icon_custom_emoji_id,
    ai.sale_price_vnd as price,
    coalesce(ai.sale_price_usdt, p.price_usdt) as price_usdt,
    coalesce(ai.original_price_vnd, p.price) as original_price,
    coalesce(ai.original_price_usdt, p.price_usdt) as original_price_usdt,
    ai.discount_percent,
    null::jsonb as price_tiers,
    coalesce(ai.promo_buy_quantity, 0) as promo_buy_quantity,
    coalesce(ai.promo_bonus_quantity, 0) as promo_bonus_quantity,
    coalesce(nullif(btrim(ai.sale_description), ''), p.description) as description,
    p.format_data,
    ai.sort_position,
    greatest(
      0,
      least(
        coalesce(rc.available_stock, 0),
        coalesce(ai.quantity_limit, 2147483647) - coalesce(rc.sold_stock, 0),
        coalesce(ai.campaign_quantity_limit, 2147483647) - coalesce(cs.sold_stock, 0)
      )
    )::bigint as stock,
    ai.campaign_name,
    ai.starts_at,
    ai.ends_at,
    coalesce(ai.per_user_limit, ai.campaign_per_user_limit) as per_user_limit,
    ai.quantity_limit,
    coalesce(rc.sold_stock, 0) as sold_quantity
  from active_items ai
  join public.sale_campaigns c on c.id = ai.campaign_id
  join public.products p on p.id = ai.product_id
  left join reservation_counts rc on rc.sale_item_id = ai.id
  left join campaign_sold cs on cs.campaign_id = ai.campaign_id
  where coalesce(p.is_deleted, false) = false
    and coalesce(p.is_hidden, false) = false
  order by
    case when ai.sort_position is null then 1 else 0 end,
    ai.sort_position nulls last,
    ai.id;
$$;

create or replace function public.get_active_sale_product(p_sale_item_id bigint)
returns table (
  sale_item_id bigint,
  sale_campaign_id bigint,
  product_id bigint,
  name text,
  telegram_icon text,
  telegram_icon_custom_emoji_id text,
  price bigint,
  price_usdt numeric,
  original_price bigint,
  original_price_usdt numeric,
  discount_percent numeric,
  price_tiers jsonb,
  promo_buy_quantity integer,
  promo_bonus_quantity integer,
  description text,
  format_data text,
  sort_position integer,
  stock bigint,
  campaign_name text,
  starts_at timestamptz,
  ends_at timestamptz,
  per_user_limit integer,
  quantity_limit integer,
  sold_quantity bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select *
  from public.get_active_sale_products()
  where sale_item_id = p_sale_item_id
  limit 1;
$$;

create or replace function public.fulfill_bot_sale_balance_purchase(
  p_user_id bigint,
  p_sale_item_id bigint,
  p_quantity integer,
  p_charge_currency text default 'vnd',
  p_order_group text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale record;
  v_balance bigint;
  v_balance_usdt numeric;
  v_quantity integer := greatest(1, coalesce(p_quantity, 0));
  v_bonus_quantity integer := 0;
  v_required_stock integer;
  v_user_limit integer;
  v_user_existing_quantity integer := 0;
  v_unit_price_vnd bigint;
  v_total_price_vnd bigint;
  v_unit_price_usdt numeric;
  v_total_price_usdt numeric;
  v_charge_currency text := lower(coalesce(nullif(btrim(p_charge_currency), ''), 'vnd'));
  v_stock_ids bigint[];
  v_reservation_ids bigint[];
  v_items jsonb;
  v_stock_count integer;
  v_order_group text;
  v_created_order_id bigint;
  v_new_balance bigint;
  v_new_balance_usdt numeric;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  perform public.release_expired_sale_stock_holds(p_sale_item_id);

  select *
  into v_sale
  from public.get_active_sale_product(p_sale_item_id);

  if not found then
    raise exception 'sale_item_not_active';
  end if;

  if coalesce(v_sale.stock, 0) < 1 then
    raise exception 'not_enough_stock';
  end if;

  insert into public.users (user_id, created_at)
  values (p_user_id, now())
  on conflict (user_id) do nothing;

  v_bonus_quantity := case
    when coalesce(v_sale.promo_buy_quantity, 0) > 0 and coalesce(v_sale.promo_bonus_quantity, 0) > 0
      then (v_quantity / v_sale.promo_buy_quantity) * v_sale.promo_bonus_quantity
    else 0
  end;
  v_required_stock := greatest(1, v_quantity + greatest(0, v_bonus_quantity));

  v_user_limit := coalesce(v_sale.per_user_limit, 0);
  if v_user_limit > 0 then
    select coalesce(sum(qty), 0)::integer into v_user_existing_quantity
    from (
      select coalesce(o.sale_paid_quantity, o.quantity, 0) as qty
      from public.orders o
      where o.user_id = p_user_id and o.sale_item_id = p_sale_item_id
      union all
      select coalesce(d.sale_paid_quantity, d.quantity, 0) as qty
      from public.direct_orders d
      where d.user_id = p_user_id
        and d.sale_item_id = p_sale_item_id
        and d.status = 'pending'
    ) used;

    if v_user_existing_quantity + v_quantity > v_user_limit then
      raise exception 'sale_user_limit_exceeded';
    end if;
  end if;

  if v_required_stock > coalesce(v_sale.stock, 0) then
    raise exception 'not_enough_stock';
  end if;

  select
    coalesce(u.balance, 0),
    coalesce(u.balance_usdt, 0)
  into v_balance, v_balance_usdt
  from public.users u
  where u.user_id = p_user_id
  for update;

  if not found then
    raise exception 'user_not_found';
  end if;

  v_unit_price_vnd := greatest(0, coalesce(v_sale.price, 0));
  v_total_price_vnd := v_unit_price_vnd * v_quantity;
  v_unit_price_usdt := greatest(0, coalesce(v_sale.price_usdt, 0));
  v_total_price_usdt := v_unit_price_usdt * v_quantity;

  if v_charge_currency = 'usdt' then
    if v_unit_price_usdt <= 0 then
      raise exception 'sale_usdt_not_available';
    end if;
    if v_balance_usdt < v_total_price_usdt then
      raise exception 'insufficient_usdt_balance';
    end if;
  else
    v_charge_currency := 'vnd';
    if v_balance < v_total_price_vnd then
      raise exception 'insufficient_balance';
    end if;
  end if;

  with locked_stock as (
    select r.id as reservation_id, s.id as stock_id, s.content
    from public.sale_stock_reservations r
    join public.stock s on s.id = r.stock_id
    where r.sale_item_id = p_sale_item_id
      and r.released_at is null
      and r.status in ('available', 'held')
      and (r.status = 'available' or coalesce(r.held_until, now() - interval '1 second') <= now())
      and coalesce(s.sold, false) = false
    order by r.id
    for update skip locked
    limit v_required_stock
  )
  select
    array_agg(ls.reservation_id order by ls.reservation_id),
    array_agg(ls.stock_id order by ls.reservation_id),
    coalesce(jsonb_agg(ls.content order by ls.reservation_id), '[]'::jsonb),
    count(*)
  into v_reservation_ids, v_stock_ids, v_items, v_stock_count
  from locked_stock ls;

  if coalesce(v_stock_count, 0) < v_required_stock then
    raise exception 'not_enough_stock';
  end if;

  update public.stock
  set sold = true
  where id = any(v_stock_ids);

  update public.users
  set balance = case when v_charge_currency = 'vnd' then coalesce(balance, 0) - v_total_price_vnd else coalesce(balance, 0) end,
      balance_usdt = case when v_charge_currency = 'usdt' then coalesce(balance_usdt, 0) - v_total_price_usdt else coalesce(balance_usdt, 0) end
  where user_id = p_user_id
  returning balance, balance_usdt into v_new_balance, v_new_balance_usdt;

  v_order_group := coalesce(
    nullif(btrim(p_order_group), ''),
    'SALE' || p_user_id::text || to_char(now(), 'YYYYMMDDHH24MISS')
  );

  insert into public.orders (
    user_id,
    product_id,
    content,
    price,
    quantity,
    order_group,
    created_at,
    sale_campaign_id,
    sale_item_id,
    sale_original_unit_price,
    sale_unit_price,
    sale_discount_amount,
    sale_paid_quantity,
    sale_bonus_quantity,
    sale_snapshot
  )
  values (
    p_user_id,
    v_sale.product_id,
    v_items::text,
    case when v_charge_currency = 'usdt' then v_total_price_vnd else v_total_price_vnd end,
    v_required_stock,
    v_order_group,
    now(),
    v_sale.sale_campaign_id,
    p_sale_item_id,
    coalesce(v_sale.original_price, v_unit_price_vnd),
    v_unit_price_vnd,
    greatest(0, coalesce(v_sale.original_price, v_unit_price_vnd) - v_unit_price_vnd),
    v_quantity,
    v_bonus_quantity,
    jsonb_build_object(
      'campaign_id', v_sale.sale_campaign_id,
      'campaign_name', v_sale.campaign_name,
      'sale_item_id', p_sale_item_id,
      'product_id', v_sale.product_id,
      'product_name', v_sale.name,
      'charge_currency', v_charge_currency,
      'sale_price_vnd', v_unit_price_vnd,
      'sale_price_usdt', v_unit_price_usdt,
      'original_price_vnd', v_sale.original_price,
      'ends_at', v_sale.ends_at
    )
  )
  returning id into v_created_order_id;

  update public.sale_stock_reservations
  set status = 'sold',
      sold_order_id = v_created_order_id,
      sold_at = now(),
      held_direct_order_id = null,
      held_until = null
  where id = any(v_reservation_ids);

  return jsonb_build_object(
    'order_id', v_created_order_id,
    'user_id', p_user_id,
    'product_id', v_sale.product_id,
    'sale_campaign_id', v_sale.sale_campaign_id,
    'sale_item_id', p_sale_item_id,
    'product_name', coalesce(nullif(btrim(v_sale.name), ''), '#' || v_sale.product_id::text),
    'description', coalesce(v_sale.description, ''),
    'format_data', coalesce(v_sale.format_data, ''),
    'quantity', v_quantity,
    'bonus_quantity', v_bonus_quantity,
    'delivered_quantity', v_required_stock,
    'order_group', v_order_group,
    'items', coalesce(v_items, '[]'::jsonb),
    'order_total_price', v_total_price_vnd,
    'charged_balance', case when v_charge_currency = 'vnd' then v_total_price_vnd else 0 end,
    'charged_balance_usdt', case when v_charge_currency = 'usdt' then v_total_price_usdt else 0 end,
    'new_balance', coalesce(v_new_balance, 0),
    'new_balance_usdt', coalesce(v_new_balance_usdt, 0),
    'charge_currency', v_charge_currency,
    'sale_ends_at', v_sale.ends_at
  );
end;
$$;

create or replace function public.create_sale_direct_order_and_get_bank_settings(
  p_user_id bigint,
  p_sale_item_id bigint,
  p_quantity integer,
  p_code text,
  p_hold_minutes integer default 10
)
returns table (
  direct_order_id bigint,
  product_id bigint,
  product_name text,
  bank_name text,
  account_number text,
  account_name text,
  quantity integer,
  bonus_quantity integer,
  unit_price bigint,
  amount bigint,
  code text,
  sale_campaign_id bigint,
  sale_item_id bigint,
  held_until timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale record;
  v_quantity integer := greatest(1, coalesce(p_quantity, 0));
  v_bonus_quantity integer := 0;
  v_required_stock integer;
  v_reservation_ids bigint[];
  v_stock_count integer;
  v_hold_until timestamptz := now() + make_interval(mins => greatest(1, coalesce(p_hold_minutes, 10)));
  v_order_id bigint;
  v_user_limit integer;
  v_user_existing_quantity integer := 0;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  perform public.release_expired_sale_stock_holds(p_sale_item_id);

  select *
  into v_sale
  from public.get_active_sale_product(p_sale_item_id);

  if not found then
    raise exception 'sale_item_not_active';
  end if;

  v_bonus_quantity := case
    when coalesce(v_sale.promo_buy_quantity, 0) > 0 and coalesce(v_sale.promo_bonus_quantity, 0) > 0
      then (v_quantity / v_sale.promo_buy_quantity) * v_sale.promo_bonus_quantity
    else 0
  end;
  v_required_stock := greatest(1, v_quantity + greatest(0, v_bonus_quantity));

  v_user_limit := coalesce(v_sale.per_user_limit, 0);
  if v_user_limit > 0 then
    select coalesce(sum(qty), 0)::integer into v_user_existing_quantity
    from (
      select coalesce(o.sale_paid_quantity, o.quantity, 0) as qty
      from public.orders o
      where o.user_id = p_user_id and o.sale_item_id = p_sale_item_id
      union all
      select coalesce(d.sale_paid_quantity, d.quantity, 0) as qty
      from public.direct_orders d
      where d.user_id = p_user_id
        and d.sale_item_id = p_sale_item_id
        and d.status = 'pending'
    ) used;

    if v_user_existing_quantity + v_quantity > v_user_limit then
      raise exception 'sale_user_limit_exceeded';
    end if;
  end if;

  if v_required_stock > coalesce(v_sale.stock, 0) then
    raise exception 'not_enough_stock';
  end if;

  with locked_stock as (
    select r.id as reservation_id
    from public.sale_stock_reservations r
    join public.stock s on s.id = r.stock_id
    where r.sale_item_id = p_sale_item_id
      and r.released_at is null
      and r.status in ('available', 'held')
      and (r.status = 'available' or coalesce(r.held_until, now() - interval '1 second') <= now())
      and coalesce(s.sold, false) = false
    order by r.id
    for update skip locked
    limit v_required_stock
  )
  select array_agg(ls.reservation_id order by ls.reservation_id), count(*)
  into v_reservation_ids, v_stock_count
  from locked_stock ls;

  if coalesce(v_stock_count, 0) < v_required_stock then
    raise exception 'not_enough_stock';
  end if;

  insert into public.direct_orders (
    user_id,
    product_id,
    quantity,
    bonus_quantity,
    unit_price,
    amount,
    code,
    payment_channel,
    created_at,
    sale_campaign_id,
    sale_item_id,
    sale_original_unit_price,
    sale_unit_price,
    sale_discount_amount,
    sale_paid_quantity,
    sale_bonus_quantity,
    sale_snapshot,
    sale_hold_until
  )
  values (
    p_user_id,
    v_sale.product_id,
    v_quantity,
    v_bonus_quantity,
    v_sale.price,
    v_sale.price * v_quantity,
    p_code,
    'vietqr',
    now(),
    v_sale.sale_campaign_id,
    p_sale_item_id,
    coalesce(v_sale.original_price, v_sale.price),
    v_sale.price,
    greatest(0, coalesce(v_sale.original_price, v_sale.price) - v_sale.price),
    v_quantity,
    v_bonus_quantity,
    jsonb_build_object(
      'campaign_id', v_sale.sale_campaign_id,
      'campaign_name', v_sale.campaign_name,
      'sale_item_id', p_sale_item_id,
      'product_id', v_sale.product_id,
      'product_name', v_sale.name,
      'sale_price_vnd', v_sale.price,
      'original_price_vnd', v_sale.original_price,
      'ends_at', v_sale.ends_at
    ),
    v_hold_until
  )
  returning id into v_order_id;

  update public.sale_stock_reservations
  set status = 'held',
      held_direct_order_id = v_order_id,
      held_until = v_hold_until
  where id = any(v_reservation_ids);

  return query
  select
    v_order_id,
    v_sale.product_id,
    v_sale.name,
    max(s.value) filter (where s.key = 'bank_name') as bank_name,
    max(s.value) filter (where s.key = 'account_number') as account_number,
    max(s.value) filter (where s.key = 'account_name') as account_name,
    v_quantity,
    v_bonus_quantity,
    v_sale.price,
    v_sale.price * v_quantity,
    p_code,
    v_sale.sale_campaign_id,
    p_sale_item_id,
    v_hold_until
  from public.settings s;
end;
$$;

create or replace function public.create_binance_sale_direct_order(
  p_user_id bigint,
  p_sale_item_id bigint,
  p_quantity integer,
  p_code text,
  p_payment_asset text,
  p_payment_network text,
  p_payment_amount_asset numeric,
  p_payment_rate_vnd numeric,
  p_payment_address text,
  p_payment_address_tag text,
  p_hold_minutes integer default 10
)
returns table (
  direct_order_id bigint,
  code text,
  payment_asset text,
  payment_network text,
  payment_amount_asset numeric,
  payment_address text,
  payment_address_tag text,
  created_at timestamptz,
  product_id bigint,
  product_name text,
  quantity integer,
  bonus_quantity integer,
  unit_price bigint,
  amount bigint,
  sale_campaign_id bigint,
  sale_item_id bigint,
  held_until timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_sale record;
  v_quantity integer := greatest(1, coalesce(p_quantity, 0));
  v_bonus_quantity integer := 0;
  v_required_stock integer;
  v_reservation_ids bigint[];
  v_stock_count integer;
  v_hold_until timestamptz := now() + make_interval(mins => greatest(1, coalesce(p_hold_minutes, 10)));
  v_order public.direct_orders%rowtype;
  v_user_limit integer;
  v_user_existing_quantity integer := 0;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  perform public.release_expired_sale_stock_holds(p_sale_item_id);

  select *
  into v_sale
  from public.get_active_sale_product(p_sale_item_id);

  if not found then
    raise exception 'sale_item_not_active';
  end if;

  v_bonus_quantity := case
    when coalesce(v_sale.promo_buy_quantity, 0) > 0 and coalesce(v_sale.promo_bonus_quantity, 0) > 0
      then (v_quantity / v_sale.promo_buy_quantity) * v_sale.promo_bonus_quantity
    else 0
  end;
  v_required_stock := greatest(1, v_quantity + greatest(0, v_bonus_quantity));

  v_user_limit := coalesce(v_sale.per_user_limit, 0);
  if v_user_limit > 0 then
    select coalesce(sum(qty), 0)::integer into v_user_existing_quantity
    from (
      select coalesce(o.sale_paid_quantity, o.quantity, 0) as qty
      from public.orders o
      where o.user_id = p_user_id and o.sale_item_id = p_sale_item_id
      union all
      select coalesce(d.sale_paid_quantity, d.quantity, 0) as qty
      from public.direct_orders d
      where d.user_id = p_user_id
        and d.sale_item_id = p_sale_item_id
        and d.status = 'pending'
    ) used;

    if v_user_existing_quantity + v_quantity > v_user_limit then
      raise exception 'sale_user_limit_exceeded';
    end if;
  end if;

  if v_required_stock > coalesce(v_sale.stock, 0) then
    raise exception 'not_enough_stock';
  end if;

  with locked_stock as (
    select r.id as reservation_id
    from public.sale_stock_reservations r
    join public.stock s on s.id = r.stock_id
    where r.sale_item_id = p_sale_item_id
      and r.released_at is null
      and r.status in ('available', 'held')
      and (r.status = 'available' or coalesce(r.held_until, now() - interval '1 second') <= now())
      and coalesce(s.sold, false) = false
    order by r.id
    for update skip locked
    limit v_required_stock
  )
  select array_agg(ls.reservation_id order by ls.reservation_id), count(*)
  into v_reservation_ids, v_stock_count
  from locked_stock ls;

  if coalesce(v_stock_count, 0) < v_required_stock then
    raise exception 'not_enough_stock';
  end if;

  insert into public.direct_orders (
    user_id,
    product_id,
    quantity,
    bonus_quantity,
    unit_price,
    amount,
    code,
    payment_channel,
    payment_asset,
    payment_network,
    payment_amount_asset,
    payment_rate_vnd,
    payment_address,
    payment_address_tag,
    created_at,
    sale_campaign_id,
    sale_item_id,
    sale_original_unit_price,
    sale_unit_price,
    sale_discount_amount,
    sale_paid_quantity,
    sale_bonus_quantity,
    sale_snapshot,
    sale_hold_until
  )
  values (
    p_user_id,
    v_sale.product_id,
    v_quantity,
    v_bonus_quantity,
    v_sale.price,
    v_sale.price * v_quantity,
    p_code,
    'binance_onchain',
    p_payment_asset,
    p_payment_network,
    p_payment_amount_asset,
    p_payment_rate_vnd,
    p_payment_address,
    nullif(p_payment_address_tag, ''),
    now(),
    v_sale.sale_campaign_id,
    p_sale_item_id,
    coalesce(v_sale.original_price, v_sale.price),
    v_sale.price,
    greatest(0, coalesce(v_sale.original_price, v_sale.price) - v_sale.price),
    v_quantity,
    v_bonus_quantity,
    jsonb_build_object(
      'campaign_id', v_sale.sale_campaign_id,
      'campaign_name', v_sale.campaign_name,
      'sale_item_id', p_sale_item_id,
      'product_id', v_sale.product_id,
      'product_name', v_sale.name,
      'sale_price_vnd', v_sale.price,
      'original_price_vnd', v_sale.original_price,
      'ends_at', v_sale.ends_at
    ),
    v_hold_until
  )
  returning * into v_order;

  update public.sale_stock_reservations
  set status = 'held',
      held_direct_order_id = v_order.id,
      held_until = v_hold_until
  where id = any(v_reservation_ids);

  return query
  select
    v_order.id,
    v_order.code,
    v_order.payment_asset,
    v_order.payment_network,
    v_order.payment_amount_asset,
    v_order.payment_address,
    v_order.payment_address_tag,
    v_order.created_at,
    v_sale.product_id,
    v_sale.name,
    v_quantity,
    v_bonus_quantity,
    v_sale.price,
    v_sale.price * v_quantity,
    v_sale.sale_campaign_id,
    p_sale_item_id,
    v_hold_until;
end;
$$;

create or replace function public.fulfill_bot_direct_order(
  p_direct_order_id bigint,
  p_order_group text default null,
  p_expire_minutes integer default 10
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.direct_orders%rowtype;
  v_product_name text;
  v_description text;
  v_format_data text;
  v_deliver_quantity integer;
  v_order_group text;
  v_stock_ids bigint[];
  v_reservation_ids bigint[];
  v_items jsonb;
  v_stock_count integer;
  v_created_order_id bigint;
  v_total_price bigint;
begin
  if not (auth.role() = 'service_role' or public.is_admin()) then
    raise exception 'forbidden';
  end if;

  select *
  into v_order
  from public.direct_orders
  where id = p_direct_order_id
  for update;

  if not found then
    raise exception 'direct_order_not_found';
  end if;

  if coalesce(v_order.status, '') <> 'pending' then
    raise exception 'direct_order_not_pending';
  end if;

  if (
      v_order.created_at is not null
      and v_order.created_at <= now() - make_interval(mins => greatest(1, coalesce(p_expire_minutes, 10)))
    )
    or (
      v_order.sale_hold_until is not null
      and v_order.sale_hold_until <= now()
    )
  then
    update public.direct_orders
    set status = 'cancelled'
    where id = v_order.id;

    if v_order.sale_item_id is not null then
      update public.sale_stock_reservations
      set status = 'available',
          held_direct_order_id = null,
          held_until = null
      where held_direct_order_id = v_order.id
        and status = 'held';
    end if;

    raise exception 'direct_order_expired';
  end if;

  select p.name, p.description, p.format_data
  into v_product_name, v_description, v_format_data
  from public.products p
  where p.id = v_order.product_id;

  v_deliver_quantity := greatest(1, coalesce(v_order.quantity, 0) + greatest(0, coalesce(v_order.bonus_quantity, 0)));
  v_order_group := coalesce(
    nullif(btrim(p_order_group), ''),
    'PAY' || v_order.user_id::text || to_char(now(), 'YYYYMMDDHH24MISS')
  );
  v_total_price := coalesce(v_order.amount, coalesce(v_order.unit_price, 0) * greatest(1, coalesce(v_order.quantity, 0)));

  if v_order.sale_item_id is not null then
    with locked_stock as (
      select r.id as reservation_id, s.id as stock_id, s.content
      from public.sale_stock_reservations r
      join public.stock s on s.id = r.stock_id
      where r.held_direct_order_id = v_order.id
        and r.sale_item_id = v_order.sale_item_id
        and r.status = 'held'
        and coalesce(s.sold, false) = false
      order by r.id
      for update skip locked
    )
    select
      array_agg(ls.reservation_id order by ls.reservation_id),
      array_agg(ls.stock_id order by ls.reservation_id),
      coalesce(jsonb_agg(ls.content order by ls.reservation_id), '[]'::jsonb),
      count(*)
    into v_reservation_ids, v_stock_ids, v_items, v_stock_count
    from locked_stock ls;

    if coalesce(v_stock_count, 0) < v_deliver_quantity then
      update public.direct_orders
      set status = 'failed'
      where id = v_order.id;

      update public.sale_stock_reservations
      set status = 'available',
          held_direct_order_id = null,
          held_until = null
      where held_direct_order_id = v_order.id
        and status = 'held';

      raise exception 'not_enough_stock';
    end if;

    update public.stock
    set sold = true
    where id = any(v_stock_ids);

    insert into public.orders (
      user_id,
      product_id,
      content,
      price,
      quantity,
      order_group,
      created_at,
      sale_campaign_id,
      sale_item_id,
      sale_original_unit_price,
      sale_unit_price,
      sale_discount_amount,
      sale_paid_quantity,
      sale_bonus_quantity,
      sale_snapshot
    )
    values (
      v_order.user_id,
      v_order.product_id,
      v_items::text,
      v_total_price,
      v_deliver_quantity,
      v_order_group,
      now(),
      v_order.sale_campaign_id,
      v_order.sale_item_id,
      v_order.sale_original_unit_price,
      v_order.sale_unit_price,
      v_order.sale_discount_amount,
      coalesce(v_order.sale_paid_quantity, v_order.quantity),
      coalesce(v_order.sale_bonus_quantity, v_order.bonus_quantity),
      coalesce(v_order.sale_snapshot, '{}'::jsonb)
    )
    returning id into v_created_order_id;

    update public.sale_stock_reservations
    set status = 'sold',
        sold_order_id = v_created_order_id,
        sold_at = now(),
        held_direct_order_id = null,
        held_until = null
    where id = any(v_reservation_ids);

    update public.direct_orders
    set status = 'confirmed'
    where id = v_order.id;

    return jsonb_build_object(
      'direct_order_id', v_order.id,
      'order_id', v_created_order_id,
      'user_id', v_order.user_id,
      'product_id', v_order.product_id,
      'sale_campaign_id', v_order.sale_campaign_id,
      'sale_item_id', v_order.sale_item_id,
      'product_name', coalesce(nullif(btrim(v_product_name), ''), '#' || v_order.product_id::text),
      'description', coalesce(v_description, ''),
      'format_data', coalesce(v_format_data, ''),
      'quantity', coalesce(v_order.quantity, 1),
      'bonus_quantity', coalesce(v_order.bonus_quantity, 0),
      'delivered_quantity', v_deliver_quantity,
      'unit_price', coalesce(v_order.unit_price, 0),
      'amount', v_total_price,
      'code', coalesce(v_order.code, ''),
      'order_group', v_order_group,
      'items', coalesce(v_items, '[]'::jsonb),
      'sale_snapshot', coalesce(v_order.sale_snapshot, '{}'::jsonb)
    );
  end if;

  with locked_stock as (
    select s.id, s.content
    from public.stock s
    where s.product_id = v_order.product_id
      and s.sold = false
    order by s.id
    for update skip locked
    limit v_deliver_quantity
  )
  select
    array_agg(ls.id order by ls.id),
    coalesce(jsonb_agg(ls.content order by ls.id), '[]'::jsonb),
    count(*)
  into v_stock_ids, v_items, v_stock_count
  from locked_stock ls;

  if coalesce(v_stock_count, 0) < v_deliver_quantity then
    update public.direct_orders
    set status = 'failed'
    where id = v_order.id;

    raise exception 'not_enough_stock';
  end if;

  update public.stock
  set sold = true
  where id = any(v_stock_ids);

  insert into public.orders (
    user_id,
    product_id,
    content,
    price,
    quantity,
    order_group,
    created_at
  )
  values (
    v_order.user_id,
    v_order.product_id,
    v_items::text,
    v_total_price,
    v_deliver_quantity,
    v_order_group,
    now()
  )
  returning id into v_created_order_id;

  update public.direct_orders
  set status = 'confirmed'
  where id = v_order.id;

  return jsonb_build_object(
    'direct_order_id', v_order.id,
    'order_id', v_created_order_id,
    'user_id', v_order.user_id,
    'product_id', v_order.product_id,
    'product_name', coalesce(nullif(btrim(v_product_name), ''), '#' || v_order.product_id::text),
    'description', coalesce(v_description, ''),
    'format_data', coalesce(v_format_data, ''),
    'quantity', coalesce(v_order.quantity, 1),
    'bonus_quantity', coalesce(v_order.bonus_quantity, 0),
    'delivered_quantity', v_deliver_quantity,
    'unit_price', coalesce(v_order.unit_price, 0),
    'amount', v_total_price,
    'code', coalesce(v_order.code, ''),
    'order_group', v_order_group,
    'items', coalesce(v_items, '[]'::jsonb)
  );
end;
$$;

grant execute on function public.release_expired_sale_stock_holds(bigint) to authenticated, service_role;
grant execute on function public.get_active_sale_products() to authenticated, service_role;
grant execute on function public.get_active_sale_product(bigint) to authenticated, service_role;
grant execute on function public.fulfill_bot_sale_balance_purchase(bigint, bigint, integer, text, text) to authenticated, service_role;
grant execute on function public.create_sale_direct_order_and_get_bank_settings(bigint, bigint, integer, text, integer) to authenticated, service_role;
grant execute on function public.create_binance_sale_direct_order(bigint, bigint, integer, text, text, text, numeric, numeric, text, text, integer) to authenticated, service_role;
grant execute on function public.fulfill_bot_direct_order(bigint, text, integer) to authenticated, service_role;
